### ISSUE TITLE
Unable to find YTDLP_Path

### ISSUE THREAD

**Issue by j0hnny432** [sim0n00ps/OF-DL#102]
I followed the video tutorial and performed the same steps, however, when I run the program, the script runs this error and terminates.

Unhandled exception. System.TypeInitializationException: The type initializer for 'OF_DL.Program' threw an exception.
 ---> Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \U. Path 'YTDLP_PATH', line 6, position 23.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program..cctor()
   --- End of inner exception stack trace ---
   at OF_DL.Program.<Main>()

**Comment by sim0n00ps** [comment]
You can't have backslashes in the paths, replace them with forward slashes

**Comment by j0hnny432** [comment]
That fixed it! Thank you!
