### ISSUE TITLE
Crash with error referencing user path that does not exist locally

### ISSUE THREAD

**Issue by mediaburnwayne** [sim0n00ps/OF-DL#133]
Been seeing random errors but consistent on this profile to crash

Downloading 1770 Posts ----------------------------------------  69% 1.8/2.5 GB 00:00:00

Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.<>c__DisplayClass14_9.<Main>b__9(List p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at OF_DL.Program.<>c__DisplayClass14_6.<<Main>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Progress.StartAsync(Func`2 action) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 96
   at OF_DL.Program.Main()

**Comment by mediaburnwayne** [comment]
This seems to be happening to any large content providers

**Comment by mediaburnwayne** [comment]
other errors


 StackTrace:    at System.Object.GetType()
   at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath)
   at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List`1 selectedProperties, Dictionary`2 users)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostMedia(String url, String folder, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at System.Object.GetType()
   at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath)
   at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List`1 selectedProperties, Dictionary`2 users)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostMedia(String url, String folder, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users)

**Comment by sim0n00ps** [comment]
> other errors
> 
> StackTrace: at System.Object.GetType() at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath) at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List`1 selectedProperties, Dictionary`2 users) at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostMedia(String url, String folder, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users) Exception caught: Object reference not set to an instance of an object.
> 
> ```
>                                                                    StackTrace:    at System.Object.GetType()
> ```
> 
> at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath) at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List`1 selectedProperties, Dictionary`2 users) at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostMedia(String url, String folder, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users)

This is related to custom file formats, do you have a format set? In releation to the other errors I don't know because I modified a few lines of that package and included it in the repo and project references, so as far as I'm aware I haven't broken it.

**Comment by mediaburnwayne** [comment]
I am going to check and make sure file formats are default, and re run

**Comment by mediaburnwayne** [comment]
So went into config and just removed anything related to file formats back to the defaults, ran against a couple of large providers and it bombs


Getting Paid Posts
Found 0 Paid Posts
Getting Posts
Found 13034 Posts

Downloading 13034 Posts ----------------------------------------  49% 18.9/38.1 GB 00:00:05

Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.<>c__DisplayClass14_9.<Main>b__9(List p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at OF_DL.Program.<>c__DisplayClass14_6.<<Main>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Progress.StartAsync(Func`2 action) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Live\Progress\Progress.cs:line 96
   at OF_DL.Program.Main()

**Comment by mediaburnwayne** [comment]
downgraded to 1.7.21 and so far so good
