### ISSUE TITLE
Unable to download videos posted since July

### ISSUE THREAD

**Issue by Thelk641** [sim0n00ps/OF-DL#138]
Trying to download all files from an account downloads everything up to the 2nd of July. For each post since then, the software shows the following error : 

Exception caught: Could not find file 'I:\Test\shinen\Posts\Free\Videos\0hfqxnzbb2iekiefewth9_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder                                                                                            Info, Medium postMedia, Auth

I've tried to run it thrice, even tried admin rights just in case, checked that there's still space left on that drive (there is), I'm out of ideas. It just seems to not be creating the files for some reason.

**Comment by sim0n00ps** [comment]
What .exe files do you have downloaded?

**Comment by Thelk641** [comment]
I think I've fixed it by updating yt-dlp. I feel dumb. 

So instead of a "it didn't work", I guess you can treat this as a "it'll help if the program caught this kind of errors and told the user to check for updates"... I'll add another comment if it throws another error message later, for now it seems to be slowly downloading something.

**Comment by Thelk641** [comment]
Download is done and can confirm : an outdated version of youtube-dl caused this.
