### ISSUE TITLE
Downloads 0

### ISSUE THREAD

**Issue by MillerTimeJones** [sim0n00ps/OF-DL#15]
I managed to get this to run but it downloads 0 of anything.

I tried one user who offered a trial not much content around 20-30 posts with 10-20 being vid/pics its shows 0 for everything.

Moved on to a free user this one had 50 posts 20-40 vid-pics again 0 in every category and this appeared

Exception caught: Value must be set.

                                    StackTrace:    at Microsoft.Data.Sqlite.SqliteParameter.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at OF_DL.Helpers.DBHelper.AddPost(String folder, Int64 post_id, String message_text, String price, Boolean is_paid, Boolean is_archived, DateTime created_at)

**Comment by sim0n00ps** [comment]
In your auth.json is everything set to true that you want to download?

**Comment by MillerTimeJones** [comment]
yes and the checks at the start shows everything is green

**Comment by sim0n00ps** [comment]
Try latest release 1.7.2, might not have any difference but worth a shot
