### ISSUE TITLE
Exception caught: Unexpected character encountered while parsing value: u. Path 'revision', line 9, position 14. 

### ISSUE THREAD

**Issue by Tg00174** [sim0n00ps/OF-DL#170]
Exception caught: Unexpected character encountered while parsing value: u. Path 'revision', line 9, position 14.

**Comment by sim0n00ps** [comment]
At what stage does this occur?

**Comment by Tg00174** [comment]
before auth

**Comment by Tg00174** [comment]
just show 3 exe file is success，then get this error

**Comment by SupahFox** [comment]
`auth.json located successfully!
config.json located successfully!
yt-dlp.exe located successfully!
ffmpeg.exe located successfully!
mp4decrypt.exe located successfully!
device_client_id_blob located successfully!
device_private_key located successfully!
Exception caught: Unexpected character encountered while parsing value: u. Path 'revision', line 9, position 14.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main()`

**Comment by sim0n00ps** [comment]
OF probably changed the response for getting a users info so will need to add the missing field when I get a chance

**Comment by sim0n00ps** [comment]
Everything should be all good now I believe, it seems it was actually nothing to do with OF and it was actually to do with the dynamic rules used to craft the headers to send to the API.
