### ISSUE TITLE
Exception caught: Could not find file

### ISSUE THREAD

**Issue by Dudeman456** [sim0n00ps/OF-DL#182]
Downloading 120 Posts ----------------------------------------   7% 0.1/1.2 GB 00:06:25
                                                                                       Exception caught: Could not find file 'R:\OFDL\__user_data__\sites\OnlyFans\ONLYFANSMODEL\Posts\Free\Videos\0hfp0zelvuxi56h46tnh6_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder                                                                                        postInfo, Medium postMedia, Auth

**Comment by Dudeman456** [comment]
Issue resolved, OS Issue.
