### ISSUE TITLE
weird error on latestbuild

### ISSUE THREAD

**Issue by BlazeVertex** [sim0n00ps/OF-DL#199]
something to do with bob i can provide more details tommorow also 

`The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.`

I got this what should i do?

**Comment by sim0n00ps** [comment]
You can try setting a higher timeout in config.json and see if that makes a difference

**Comment by sim0n00ps** [comment]
Log out and back into OF, copy your new sess value to auth.json and re-try

**Comment by sim0n00ps** [comment]
Have you generated the 2 files needed to download DRM videos?

**Comment by Minehors** [comment]
> Have you generated the 2 files needed to download DRM videos?

so it means every file is drm locked? i dint yet tried it

**Comment by sim0n00ps** [comment]
If you're getting that error then that indicates that the video has DRM on it and therefore you need the device_client_id_blob and device_private_key files, there's a guide linked in the readme you can use to get those 2 files

**Comment by Minehors** [comment]
> If you're getting that error then that indicates that the video has DRM on it and therefore you need the device_client_id_blob and device_private_key files, there's a guide linked in the readme you can use to get those 2 files
i get constant this: 
```
C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\dumper-main>python3 ./dump_keys.py
Traceback (most recent call last):
  File "C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Device import Device
  File "C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\dumper-main\Helpers\Device.py", line 5, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by Minehors** [comment]
```
frida-server-16.1.4-android-x86: 1 file pushed, 0 skipped. 277.5 MB/s (51624572 bytes in 0.177s)
/system/bin/sh: <stdin>[1]: su: not found
Unable to load SELinux policy from the kernel: Failed to open file ?/sys/fs/selinux/policy?: Permission denied
```

```
Environment variable C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\ not defined
De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist.
2023-10-26 07:58:46 PM - main - 32 - INFO - Connected to Android Emulator 5554
2023-10-26 07:58:46 PM - main - 33 - INFO - Scanning all processes
Traceback (most recent call last):
  File "C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\dumper-main\dump_keys.py", line 43, in <module>
    main()
  File "C:\Users\Mr.Fox\Downloads\Compressed\dumper-main\dumper-main\dump_keys.py", line 35, in main
    for process in device.usb_device.enumerate_processes():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mr.Fox\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mr.Fox\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 887, in enumerate_processes
    return self._impl.enumerate_processes(**kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.ProcessNotFoundError: unable to find process with name 'system_server'
```
