### ISSUE TITLE
Couldn't find post

### ISSUE THREAD

**Issue by rando2347** [sim0n00ps/OF-DL#202]
Stumbled on a problem, the other videos seem to download properly, but this particular video had issues.

Exception caught: Input string '2.37' is not a valid integer. Path 'tipsAmountRaw', line 1, position 1286.

                                                                                                          StackTrace:    at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at OF_DL.Helpers.APIHelper.GetPost(String endpoint, String folder, Auth auth, Config config)
Couldn't find post

**Comment by Wandererinchaos007** [comment]
Giving this thread a bump. I have the same problem too. Did you discover any workarounds or fixes? @sim0n00ps please help.

**Comment by sim0n00ps** [comment]
https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.40
