### ISSUE TITLE
Set-up following the video to the T, go to run and it closes instantly.

### ISSUE THREAD

**Issue by brazenCoding** [sim0n00ps/OF-DL#203]
I run the OF DL.exe and it shows one line in green for finding the auth.json then closes.
Double-checked that I converted all back slashes to forward slashes.
Double-checked paths to EXEs.
Triple-checked Runtime and VC distributables were installed (they were)
Can't figure out what's wrong.

**Comment by Cicciolin0** [comment]
This is my first time using this, but  I am also having the same issue

**Comment by sim0n00ps** [comment]
If you could screen record/screenshot what you see when you double click the exe that would be helpful

**Comment by sim0n00ps** [comment]
If you could please try the latest version which can be found here https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.41. This version includes logging, this will log any exceptions to a txt file which can be found in the `logs` folder wherever you have OF DL.exe located

**Comment by Cicciolin0** [comment]
> If you could please try the latest version which can be found here https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.41. This version includes logging, this will log any exceptions to a txt file which can be found in the `logs` folder wherever you have OF DL.exe located

this is the error:
2023-10-28 23:08:56.821 -03:00 [ERR] Exception caught: Bad JSON escape sequence: \y. Path 'YTDLP_PATH', line 6, position 27.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program.Main()

**Comment by sim0n00ps** [comment]
You have a backslash in your yt-dlp path, make sure you replace any backslashes with forwardslashes

**Comment by Cicciolin0** [comment]
> You have a backslash in your yt-dlp path, make sure you replace any backslashes with forwardslashes. Check the other paths for this as well.

Sorry about that, as I've said it was my first time using any tool like this. Now it's working perfectly, thanks!!
