### ISSUE TITLE
Problem downloading DRM  Exception caught: Could not find file 

### ISSUE THREAD

**Issue by czl96** [sim0n00ps/OF-DL#239]
Exception caught: Could not find file 'F:\0823\1\__user_data__\sites\OnlyFans\cccouple69\Posts\Free\Videos\0hl4xi8zlqfrczzacfmp2_source.mp4'.

                                                                                                        StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id,                                                                                    thor author, Dictionary`2 users, ConfDownloading Post ----------------------------------------   0% 87.2 MB 00:00:00

Problem downloading DRM Exception caught: Could not find file 
Can you tell me what to do？

**Comment by ardencod3** [comment]
same here. it happend only on DRM video

**Comment by lucacham** [comment]
same here

**Comment by crazyslovakian** [comment]
Just download the most recent version of `ffmpeg.exe` and it fixes the issue (make sure the `auth.json` also points to this new version)

**Comment by wioch** [comment]
Did you get the **device_client_id_blob** and **device_private_key** files into _cdm_ directory ?

**Comment by sim0n00ps** [comment]
> Did you get the **device_client_id_blob** and **device_private_key** files into _cdm_ directory ?

Those 2 files are no longer a requirement for the script to run, but it probably is still worth generating them if cdrm-project goes down again

**Comment by lucacham** [comment]
> Just download the most recent version of `ffmpeg.exe` and it fixes the issue (make sure the `auth.json` also points to this new version)

I updated the latest version of ffmpeg.exe ([Latest Auto-Build (2023-12-30 12:54)]) and it still prompts this error

**Comment by ardencod3** [comment]
> I updated the latest version of ffmpeg.exe ([Latest Auto-Build (2023-12-30 12:54)]) and it still prompts this error

same to me. look like it started to work and downloading but turn out error in few minutes later.
I will try again today with version before the current latest one.
