### ISSUE TITLE
What is the reason why it crashes when running OF DL.exe?

### ISSUE THREAD

**Issue by lucacham** [sim0n00ps/OF-DL#244]
I have filled in auth.json as required, but a crash occurs when running OF DL.exe. I don’t know the reason.

**Comment by sim0n00ps** [comment]
Have you installed this https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.14-windows-x86-installer?cid=getdotnetcore

**Comment by lucacham** [comment]
> Have you installed this https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.14-windows-x86-installer?cid=getdotnetcore
Thank you, I downloaded the video successfully. But can’t download DRM videos

**Comment by NoisyNinja343** [comment]
Adding to this issue as I'm still having this problem even after downloading the 7.0.14 .NET.
I've done the following:

- [X] Re-downloaded the .zip file
- [X] Re-downloaded .NET
- [X] Logged in and out of OF to ensure sess id and xbc didn't change
- [X] Restarted computer
- [X] Confirmed auth and config files are correct with auth_id; sess_id; and xbc
- [X] Cried when the program closed for the 11th time in a row

Logs with the errors

2023-12-31 15:08:42.237 -05:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
2023-12-31 15:08:42.270 -05:00 [ERR] Inner Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2023-12-31 15:08:42.271 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main()
2023-12-31 15:09:54.922 -05:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetAllSubscriptions(Dictionary`2 getParams, String endpoint, Auth auth)
2023-12-31 15:09:54.956 -05:00 [ERR] Inner Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2023-12-31 15:09:54.957 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.DownloadAllData()
   at OF_DL.Program.Main()

**Comment by sim0n00ps** [comment]
Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.

**Comment by lucacham** [comment]
> Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.

How do I need to set the proxy in config?

**Comment by sim0n00ps** [comment]
> > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> 
> How do I need to set the proxy in config?
> 

There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL

**Comment by lucacham** [comment]
> > > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> > 
> > 
> > How do I need to set the proxy in config?
> 
> There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL

I have VPN turned on, but downloading DRM videos still fails!
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/2a4f877e-df03-4307-994e-22fba26e759b)

I can successfully download non-DRM videos
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/1a244ac7-c0a3-456d-a726-d50fcbf40c67)

**Comment by lucacham** [comment]
> > > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> > 
> > 
> > How do I need to set the proxy in config?
> 
> There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL

I have VPN turned on but still can't download DRM videos
I can download non-DRM videos
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/06bd7087-cd1d-4255-946d-96faae38cca8)

DRM video download will error out
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/078ed0a9-dfab-494b-9019-4468842716cf)

**Comment by lucacham** [comment]
> Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.

Thank you, it works, I set proxy as global proxy and I just successfully downloaded 2 videos with DRM
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/b9e8033f-7a75-43b8-92e4-d16b0acd8d0e)

**Comment by lucacham** [comment]
> > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.

Thank you, it works, I set proxy as global proxy and I just successfully downloaded 2 videos with DRM 

![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/547eb8c1-684f-4cfd-a1df-e2cc7c64278c)

**Comment by lucacham** [comment]
> > > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> > 
> > 
> > How do I need to set the proxy in config?
> 
> There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL

I exited the terminal during the download, but when I re-download, it will prompt Post *** already downloaded. In this case, how can I re-download the video of this post?
![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/092f876a-ceae-4a2d-b22e-7e8e924da26b)

**Comment by sim0n00ps** [comment]
> > > > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> > > 
> > > 
> > > How do I need to set the proxy in config?
> > 
> > There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL
> 
> I exited the terminal during the download, but when I re-download, it will prompt Post *** already downloaded. In this case, how can I re-download the video of this post?
> ![image](https://github.com/sim0n00ps/OF-DL/assets/25399625/092f876a-ceae-4a2d-b22e-7e8e924da26b)
> 

I would delete the metadata folder and the actual video file, then re-run the scrape, that should download it again

**Comment by lucacham** [comment]
> > > > > Any exceptions to do with SSL Certificates I can't do anything about. It's usually down to your ISP so I would advise using a VPN.
> > > > 
> > > > 
> > > > How do I need to set the proxy in config?
> > > 
> > > 
> > > There is no way to put a proxy in the config. You just need to have the VPN running on your PC and then run OF DL
> > 
> > 
> > I exited the terminal during the download, but when I re-download, it will prompt Post *** already downloaded. In this case, how can I re-download the video of this post?
> > ![image](https://private-user-images.githubusercontent.com/25399625/293572865-092f876a-ceae-4a2d-b22e-7e8e924da26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDY4MzcsIm5iZiI6MTcwOTYwNjUzNywicGF0aCI6Ii8yNTM5OTYyNS8yOTM1NzI4NjUtMDkyZjg3NmEtY2VhZS00YTJkLWIyMmUtN2U4ZTkyNGRhMjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyNDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NzY4ZTc0ZmU0MDU3MWI4ZTMyMTAxNjhjZjEyZmMxMGZkMWZmMzA5ZTQ1MjVjZWI0NDdhZDZlMWM4NjAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tpAoJjRfiZYUAhxekVxWAJlZtBYrRuopozDuzy78q0U)
> 
> I would delete the metadata folder and the actual video file, then re-run the scrape, that should download it again

Late reply. At that time I solved the problem, including the download of DRM. You can close this post, thank you
