### ISSUE TITLE
Path is not accessible

### ISSUE THREAD

**Issue by waltersz1404** [sim0n00ps/OF-DL#245]
OF-DL cannot find ffmpeg path. I've tried saving the ffmpeg.exe in multiple folders with no luck. Changed all the slashes. Not sure what I've missed.

**Comment by sim0n00ps** [comment]
What have you put in auth.json as the path?

**Comment by waltersz1404** [comment]
it is currently in c drive

**Comment by waltersz1404** [comment]
C:/ffmpeg.exe thats what i get atm

**Comment by sim0n00ps** [comment]
Create a folder in the root of C:/ and put ffmpeg in that, change the path and see if that helps

**Comment by waltersz1404** [comment]
same error. Could it be my computer?

**Comment by waltersz1404** [comment]
C:/Download/ffmpeg.exe this is my current path

**Comment by sim0n00ps** [comment]
Is OF DL on your C:/ drive or another drive?

**Comment by waltersz1404** [comment]
same drive, different folder

**Comment by sim0n00ps** [comment]
This is my setup:
auth.json
`"FFMPEG_PATH": "E:/OnlyFans/DRMEXES/ffmpeg.exe"`
![image](https://github.com/sim0n00ps/OF-DL/assets/132307467/676d297c-3d0c-44ba-afda-5d4d0328bfbb)
![image](https://github.com/sim0n00ps/OF-DL/assets/132307467/36301511-06e5-4a9b-9d91-3515db69abc7)

**Comment by waltersz1404** [comment]
i tried copying your set up. no dice.

**Comment by sim0n00ps** [comment]
Right click the exe and run as administrator? Running out of things you can do

**Comment by waltersz1404** [comment]
ran ffmpeg as admin, authorization popped up but nothing happened afterwards.

ran OF-DL as admin; same error

**Comment by sim0n00ps** [comment]
Maybe try a different drive if you can?

**Comment by waltersz1404** [comment]
would a USB be acceptable?

**Comment by waltersz1404** [comment]
i put everything on a USB, and the path is still not accessible

**Comment by melithine** [comment]
What's the exact error?

**Comment by waltersz1404** [comment]
The provided path  does not exist or is not accessible.
Cannot locate ffmpeg.exe; please modify auth.json with the correct path. Press any key to exit.

auth.json and config.json are both green

**Comment by githubuser9542** [comment]
I'm having the same exact issue, did you ever figure it out?

**Comment by bzayas** [comment]
I'm running into the exact issue, I've tried everything described above. I did however run the exe from an admin command prompt so that I can see any errors. Below is the output I observed. 

`C:\temp\OF.DL.V1.7.48>"OF DL.exe"
 __        __         _                                       _                ___    _____           ____    _
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___      / _ \  |  ___|         |  _ \  | |
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \    | | | | | |_     _____  | | | | | |
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |   | |_| | |  _|   |_____| | |_| | | |___
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/     \___/  |_|             |____/  |_____|

auth.json located successfully!
Exception caught: Bad JSON escape sequence: \O. Path 'FFMPEG_PATH', line 6, position 27.

                                                                                        StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program.Main()

C:\temp\OF.DL.V1.7.48>`

**Comment by sim0n00ps** [comment]
To me that indicates that you have back slashes in your path, you need to replace them with /

**Comment by bzayas** [comment]
Totally missed that tiny detail. Thank you for your help.
