### ISSUE TITLE
 [ERR] Exception caught: Response status code does not indicate success: 429 (Too Many Requests).

### ISSUE THREAD

**Issue by rstein2023** [sim0n00ps/OF-DL#267]
Getting the following error after successfully authenticating - 
2024-01-28 16:27:29.663 -05:00 [ERR] Exception caught: Response status code does not indicate success: 429 (Too Many Requests).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetAllSubscriptions(Dictionary`2 getParams, String endpoint, Auth auth)
2024-01-28 16:27:29.698 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.DownloadAllData()
   at OF_DL.Program.Main()

Program runs for a couple minutes then errors out and closes.

**Comment by moisty123** [comment]
I have the same problem. Were you able to find a solution?
