### ISSUE TITLE
error when attempting to download certain files

### ISSUE THREAD

**Issue by rakuko1** [sim0n00ps/OF-DL#270]
recently downloaded the new version to see if it helped with a separate error i was receiving, started noticing this kind of error was showing up for most files I downloaded:

```
2024-01-31 16:11:09.673 -08:00 [ERR] Exception caught: Could not find file '[filepath]\0hf2t147dv4an99q2w9xl_source.mp4'.

StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users, Config config, Boolean showScrapeSize)
```

presumably just a minor check error due to config renaming the files after download, but figured I'd report. the files are fine, it just pops up for every individual file.

**Comment by rakuko1** [comment]
it's still happening on occasion, this time for some purchased videos. does download the rest of the videos but not certain ones oddly.

**Comment by rakuko1** [comment]
ok, updated to newest version, error has changed to this:

`Exception caught: Cannot start process because a file name has not been provided.

                                   StackTrace:    at System.Diagnostics.Process.Start()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize, Config config)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedMessageDRMVideo(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, Progres                                                                          FromUser fromUser, Dictionary`2 users, Config`

**Comment by melithine** [comment]
I think that's throwing an error when trying to locate ffmpeg. Double check your configuration and make sure that you have the correct path set for `ffmpeg.exe` (remember that the path needs to use forward slashes, not backslashes). I think you might not have that set currently, and that is used specifically when dealing with videos that have DRM, which would explain why it's only happening on some content.

**Comment by rakuko1** [comment]
the second error might have been because of the ffmpeg.exe path because of shifting from auth.json to config.json. that being said, for those same files i get the original error:

2024-02-22 09:40:55.766 -08:00 [ERR] Exception caught: Could not find file '[folder]\Messages\Free\Videos\0hhizz9fdwgfzkloy40x7_source.mp4'.

StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize, Config config)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users, Config config, Boolean showScrapeSize)


if it's a DRM issue, it is a selective DRM issue because i am able to download some DRM videos.

**Comment by rakuko1** [comment]
i downloaded the latest ffmpeg, that did it. was on a 2021 version.
