### ISSUE TITLE
Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by moisty123** [sim0n00ps/OF-DL#277]
Happens to only a few accounts:

Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, Auth auth, Config config, List`1 paid_post_ids)

Any idea on what it could be? Thanks.

**Comment by deadbeatdandylyon** [comment]
Just attempted to scrape and also receiving the same error message. 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/639d5805-6eef-4cc5-9f22-01bcae31c630)

**Comment by sim0n00ps** [comment]
That's an issues on OF's end, nothing I can do
