### ISSUE TITLE
Error when downloading content from a model

### ISSUE THREAD

**Issue by greyhat94** [sim0n00ps/OF-DL#282]
I have downloaded successfully the content of a model. Then, I started doing the same with another creator. However, I have got this error, and I don't know how to fix it up: 

                                                                 
 ```
Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh, Auth auth)

Inner Exception:
Exception caught:  Received an unexpected EOF or 0 bytes from the transport stream.

StackTrace:    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id,                                                                   stMedia, Author author, Dictionary`2 users, Config con
Downloading 76 Posts ----------------------------------------   0%
```

Please, help me. I rely on your support. I encounter this issue when using VPN and without it.

**Comment by greyhat94** [comment]
I am using SurfShark VPN.

Il dom 18 feb 2024, 20:20 sim0n00ps ***@***.***> ha scritto:

**Comment by sim0n00ps** [comment]
I use NordVPN and face 0 issues, so maybe try that or any other VPN provider

**Comment by greyhat94** [comment]
I've noticed another strange issue. I don't know if it depends on DRM or something like that, but it looks like it detects less media files than the originals. For example, if the model has 365 videos, the scraper detects that she post 341 videos.

**Comment by melithine** [comment]
> I've noticed another strange issue. I don't know if it depends on DRM or something like that, but it looks like it detects less media files than the originals. For example, if the model has 365 videos, the scraper detects that she post 341 videos.

I suspect that some of them would be considered `PaidPosts` (PPV posts that require unlocking) and some of them would just be `Posts`.

**Comment by greyhat94** [comment]
> > I've noticed another strange issue. I don't know if it depends on DRM or something like that, but it looks like it detects less media files than the originals. For example, if the model has 365 videos, the scraper detects that she post 341 videos.
> 
> I suspect that some of them would be considered `PaidPosts` (PPV posts that require unlocking) and some of them would just be `Posts`.

Thanks for your prompt response. Is this type of detection correct or could it be a software processing error regarding the type of content, which can be blocked or free?

**Comment by melithine** [comment]
> > I suspect that some of them would be considered `PaidPosts` (PPV posts that require unlocking) and some of them would just be `Posts`.
> 
> Thanks for your prompt response. Is this type of detection correct or could it be a software processing error regarding the type of content, which can be blocked or free?

OF-DL's logic is correct. `PaidPosts` only consist of posts on the model's timeline that you have to unlock with $. `PaidMessages` are the same, just on the message view instead of the timeline. Anything else is considered free, because OF-DL can't associate however you may have tipped for something with whatever content the model sent in return. The `Paid` description in OF-DL specifically only refers to unlockable PPV content. 

if i recall correctly, OF has a vault feature that contains all the stuff you purchased from PPVs, which persists even after the model has retired and taken their content down from the platform entirely. Items sent by a model in exchange for things like tipping on a goal, or a vote, or a campaign do not count towards that feature, and that content _would_ be lost if the model retires and takes down their content completely.  Directly unlocked PPVs would remain accessible even after that point.

**Comment by sim0n00ps** [comment]
> I've noticed another strange issue. I don't know if it depends on DRM or something like that, but it looks like it detects less media files than the originals. For example, if the model has 365 videos, the scraper detects that she post 341 videos.

Duplicate media that has the same ID, any dupes are skipped and only downloaded once, that is why you might see a mismatch with the counts

**Comment by topzs123** [comment]
Hey @sim0n00ps regarding to media with same ID, is it any way to fix this? I have 3 messages that i´m trying to download but sometimes program only shows 2, and some other times shows 3 messages but only downloads 2, skipping a video.... How could we fix this?
Maybe it has something to do with DRM? (i´ve already tryied DRM downloader too but still not working)
![image](https://github.com/sim0n00ps/OF-DL/assets/171200413/85b249cb-56e0-400c-87ae-e3f1167a774a)
![image](https://github.com/sim0n00ps/OF-DL/assets/171200413/e913f197-10d2-43d2-bc4a-2d30adece043)
