### ISSUE TITLE
The command prompt window appear and close immediately

### ISSUE THREAD

**Issue by icemessenger** [sim0n00ps/OF-DL#308]
It was fine until yesterday, when double click to run the program, the command prompt window appear and close immediately. I cannot even read what was written. This is the log, not sure what is going on tho. Any idea what's wrong here? 

Thank you. 

====

2024-03-16 08:57:08.701 +08:00 [ERR] Exception caught: After parsing a value an unexpected character was encountered: ". Path 'COOKIE', line 6, position 2.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program.Main()

**Comment by icemessenger** [comment]
The error, Path 'COOKIE', line 6, position 2, What's wrong with my COOKIE?

=====


{
  "USER_ID": "516XXXX",
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "X_BC": "45007a4af78XXXXXXXX3042dc8b8b6aa446f",
  "COOKIE": "auth_id=516XXXX; sess=qfn7m3d080n8nj0XXXXXXXXXXum;"
  "FFMPEG_PATH": "F:/ffmpeg.exe"
}

**Comment by melithine** [comment]
The problem is your JSON syntax is wrong... missing the comma at the end of the `COOKIE` line, since it's not the last element of the array, `FFMPEG_PATH` is. If you edit JSON files in something like VSCode or Notepad++, the syntax highlighting can make those kinds of errors much more obvious.

**Comment by icemessenger** [comment]
Omg, THANK YOUUUUUU!
