### ISSUE TITLE
dump_keys.py python Issue

### ISSUE THREAD

**Issue by Mnu-Hdez** [sim0n00ps/OF-DL#314]
When I try to execute the command in python I got all this errors about the file and it cannot start

Traceback (most recent call last):
  File "C:\Users\Manu Hdez\Downloads\dumper-main\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\Users\Manu Hdez\Downloads\dumper-main\dumper-main\Helpers\Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "C:\Users\Manu Hdez\Downloads\dumper-main\dumper-main\Helpers\wv_proto2_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\descriptor_pb2.py", line 1855, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.descriptor_pb2', globals())
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\python_message.py", line 198, in __init__
    _AddPropertiesForFields(descriptor, cls)
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\python_message.py", line 586, in _AddPropertiesForFields
    _AddPropertiesForField(field, cls)
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\python_message.py", line 612, in _AddPropertiesForField
    _AddPropertiesForRepeatedField(field, cls)
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\python_message.py", line 668, in _AddPropertiesForRepeatedField
    setattr(cls, property_name, _FieldProperty(field, getter, setter, doc=doc))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manu Hdez\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\protobuf\internal\python_message.py", line 623, in __init__
    property.__init__(self, getter, setter, doc=doc)
AttributeError: '_FieldProperty' object attribute '__doc__' is read-only

**Comment by Mnu-Hdez** [comment]
I tried first downgrading protobuf to 3.20.3 and doesnt do anything

**Comment by melithine** [comment]
https://github.com/lollolong/dumper is where that needs to be reported, not here.
