### ISSUE TITLE
Can't Download DRM Videos

### ISSUE THREAD

**Issue by Mellomama** [sim0n00ps/OF-DL#324]
I get this error with every one before it skips to the next file.

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp, Auth auth)
2024-04-05 00:29:48.845 -05:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

I've tried multiple VPNs, multiple VPN connection types, with the 2 device files and without, multiple versions as well as just my base internet connection. At a bit of a loss. This is a relatively new issue, any help would be appreciated.

**Comment by melithine** [comment]
Try the most rec3nt version.
