### ISSUE TITLE
StackTrace crash?

### ISSUE THREAD

**Issue by SmokeyOdin** [sim0n00ps/OF-DL#342]
when opening just crashes with this in the log file:

2024-04-25 21:04:16.453 +01:00 [ERR] Exception caught: The format of value 'OPR/108.0.0.0
' is invalid.

StackTrace:    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
2024-04-25 21:04:16.471 +01:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main()

**Comment by melithine** [comment]
Please paste the `USER_AGENT` portion of your `config.json`.

**Comment by SmokeyOdin** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 OPR/108.0.0.0

**Comment by melithine** [comment]
You have quotes around that entire thing? Because that's two lines, and the user agent should not contain a new line itself within the quotes. That's not formatted correctly.

**Comment by SmokeyOdin** [comment]
it was all on one line but the ending ", was on a new line, moving to the end made it work.

thanks
