### ISSUE TITLE
Exception caught: SQLite Error 19

### ISSUE THREAD

**Issue by marcusw89** [sim0n00ps/OF-DL#360]
Hi,

Every time I open I get the following after successful login

Exception caught: SQLite Error 19: 'UNIQUE constraint failed: users.username'.

StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at OF_DL.Helpers.DBHelper.CreateUsersDB(Dictionary`2 users)

**Comment by melithine** [comment]
I've never seen this, but it sounds like you might have upgraded too many versions in one go and a db migration was missed. I'd try removing the users database (`config/users.db`) and trying again.

**Comment by marcusw89** [comment]
Deleting users.db seemed to solve it. Thanks.
