### ISSUE TITLE
Exception caught: Invalid property identifier character: {. Path '', line 1, position 1.

### ISSUE THREAD

**Issue by bondo01** [sim0n00ps/OF-DL#364]
(base) PS F:\temp> .\OF_DL.exe
 __        __         _                                       _
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/

   ___    _____           ____    _
  / _ \  |  ___|         |  _ \  | |
 | | | | | |_     _____  | | | | | |
 | |_| | |  _|   |_____| | |_| | | |___
  \___/  |_|             |____/  |_____|

auth.json located successfully!
Exception caught: Invalid property identifier character: {. Path '', line 1, position 1.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program.Main()
-----------------------------------------------------------------------------
Version OF.DL.V1.7.56
OS Windows 11 Ver = 23H2 build = 22631.3593

I switched to new version when problems with 405 errors with V1.7.52 today. worked fine 2 days ago.
 Exception caught: Response status code does not indicate success: 405 (METHOD NOT ALLOWED).

I added and removed commas on the last line of the auth.json and config.json files.

Did the format for the file paths change between 52->56??? notably DownloadPath and FFmpegPath?

**Comment by melithine** [comment]
The ffmpeg path can be specified in `auth.json` still, but it's more accurately in `config.json` now. That said, your JSON isn't valid. If you open it in Notepad++ or VSCode, the syntax highlighting should indicate where it is being broken. Or just generate the `auth.json` using the browser extension @whimsical-c4lic0 provides.

**Comment by bondo01** [comment]
I did use the browser extension to gather the auth.json config.
bondo

**Comment by melithine** [comment]
Were you able to solve this? If not, paste a redacted version (cut out a few characters from the middle of the values, nothing near the quotes/commas and your full config.json.

**Comment by bondo01** [comment]
I'm no longer seeing this issue. I could not cut and past the contents from
the addon. I used the save auth.json in the addon to create the file and
that worked. No it fails for:
       Exception caught: Response status code does not indicate success:
403 (Forbidden).

bondo
