### ISSUE TITLE
OF DL V1.7.57: "500 Internal Server Error"

### ISSUE THREAD

**Issue by tnpir4002** [sim0n00ps/OF-DL#366]
Error:

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh, Auth auth)
2024-05-29 18:27:49.021 -04:00 [ERR] Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

**Comment by sim0n00ps** [comment]
Use latest version
