### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#376]
Everything works perfectly. Thank you for scraper.
The only thing is that I got an error once and I decided to tell you

Input #0, dash, from 'https://cdn3.onlyfans.com/dash/files/c/cc/(hidden)/0hp4bazo7c3vhy8vgngm2.mpd':
  Duration: 00:08:18.00, start: 0.000000, bitrate: 0 kb/s
  Program 0 
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 1080x1920 [SAR 1:1 DAR 9:16], 9813 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default)
      Metadata:
        variant_bitrate : 8500000
        id              : 1
      Side data:
        unknown side data type 24 (768 bytes)
  Stream #0:1: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 404x720 [SAR 1:1 DAR 101:180], 5968 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default)
      Metadata:
        variant_bitrate : 5000000
        id              : 2
      Side data:
        unknown side data type 24 (768 bytes)
  Stream #0:2: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, bottom first), 134x240 [SAR 1:1 DAR 67:120], 416 kb/s, 14.99 fps, 14.99 tbr, 90k tbn (default)
      Metadata:
        variant_bitrate : 400000
        id              : 3
      Side data:
        unknown side data type 24 (768 bytes)
  Stream #0:3(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (default)
      Metadata:
        variant_bitrate : 96000
        id              : 4
      Side data:
        unknown side data type 24 (768 bytes)
[AVFormatContext @ 000002a147745ac0] Unable to choose an output format for '1'; use a standard extension for the filename or specify the format manually.
[out#0 @ 000002a143e2e2c0] Error initializing the muxer for 1: Invalid argument
Error opening output file 1.
Error opening output files: Invalid argument

2024-06-03 02:53:34.578 +03:00 [ERR] Exception caught: Could not find file 'E:\OF.DL.V1.7.58\__user_data__\sites\OnlyFans\caju\Posts\Free\Videos\0hp4bazo7c3vhy8vgngm2_source.mp4'.

StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize, Config config)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users, Config config, Boolean showScrapeSize)

**Comment by melithine** [comment]
That's all error info from ffmpeg. Try a different version, maybe?

**Comment by bezaaas** [comment]
i'm using the latest version of ffmpeg and it work well, maybe something wrong with the video because this issues i seen only one time.
