### ISSUE TITLE
Getting error on some files

### ISSUE THREAD

**Issue by root3d1** [sim0n00ps/OF-DL#40]
Hi,
This tool is great for full scrapes much easier than any i have used in the past however i get this error on some files which i assume is to do with drm. Is this tool supposed to be able to download these files or am i out of luck?

This is the error i get : Exception caught: No connection could be made because the target machine actively refused it. (cdrm-project.com:443)
StackTrace:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No connection could be made because the target machine actively refused it.

StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

Thanks!

**Comment by sim0n00ps** [comment]
I think a few have had this issue before it might be down to an antivirus blocking the site, it is trustworthy so might be worth adding the site to a whitelist or disable the antivirus and give it another try

**Comment by root3d1** [comment]
> I think a few have had this issue before it might be down to an antivirus blocking the site, it is trustworthy so might be worth adding the site to a whitelist or disable the antivirus and give it another try

Thank you so much my firewall was blocking it in the background when it usually notifies me that has solved it!
