### ISSUE TITLE
Software exits right away with an error about device_client_id_blob and/or device_private_key missing

### ISSUE THREAD

**Issue by Ragnarok700** [sim0n00ps/OF-DL#403]
Everything was going well for over a month of weekly use. Took a break for two weeks and starting it again today (2024-06-12) and I get this in the terminal before the software closes near-instantly:
```
auth.json located successfully!
config.json located successfully!
FFmpeg located successfully. Path auto-detected: T:\Users\Ragnarok\Downloads\OF.DL.V1.7.54\ffmpeg.exe
device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM
protected videos
```

The logs show this:
```
2024-06-12 12:10:00.665 -04:00 [ERR] Exception caught: Response status code does not indicate success: 404 (Not Found).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
2024-06-12 12:10:00.697 -04:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main()
```

Of course, I did update my auth.json as usual and after hitting the issue a few times I upgraded my ffmpeg just in case, but it did not help.

I also figured maybe there was something wrong in my folder structure, so I extracted a new version elsewhere and tried again but it also fails the same way, too.

Any ideas would be greatly appreciated!

**Comment by legendaryredfox** [comment]
Refer to this issue: https://github.com/sim0n00ps/OF-DL/issues/397
