### ISSUE TITLE
Unable to download purchase tab (JSON parsing error)

### ISSUE THREAD

**Issue by myacct123** [sim0n00ps/OF-DL#405]
I'm using 1.7.60 and trying to download the purchase tab

I believe my configs are all correct. This error happens after successful auth. Thank you for any help!

```
Valid version of Windows found.
auth.json located successfully!
config.json located successfully!
FFmpeg located successfully
device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM
protected videos
Logged In successfully as removed
Exception caught: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.

  StackTrace:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at OF_DL.Helpers.APIHelper.GetUserInfoById(String endpoint)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.APIHelper.GetPurchasedTabUsers(String endpoint, IDownloadConfig config, Dictionary`2 users)
Checking folders for Users in Purchased Tab
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config)
   at OF_DL.Program.Main(String[] args)

Press any key to exit.
```

**Comment by myacct123** [comment]
Downloading for individual users works. I believe the issue might be the large number of purchases I have. Thanks again for any help.

**Comment by thatcoderguy** [comment]
Are there any users who you've purchased content from that have since closed their account?

**Comment by thatcoderguy** [comment]
I've just written a fix for this, I'll create a pull request now... but I don't know when the next release will be, but if you know how to code in C# you should be able to pull the code and build the fix.

**Comment by myacct123** [comment]
That's ok. I can wait. You're amazing!!
