### ISSUE TITLE
CDRM project not working

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#418]
[ERR] Exception caught: An attempt to establish a connection was unsuccessful because... the required response was not received from another computer within the required time, or an already established connection was terminated due to an incorrect response from an already connected computer. (cdrm-project.com:443)

StackTrace:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-06-17 13:11:59.217 +03:00 [ERR] Inner Exception: An attempt to establish a connection was unsuccessful because... the required response was not received from another computer within the required time, or an already established connection was terminated due to an incorrect response from an already connected computer.

StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-06-17 13:11:59.298 +03:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users)

**Comment by Astercholik** [comment]
I've had this error for 3 hours, but I've noticed that when downloading the same post again, the error appears once and once not, so I guess there's some kind of overload on OnlyFans.

**Comment by melithine** [comment]
If you're hitting bad timeouts, you can increase that in the `config.json`.  F4om the docs:

>`Timeout`:
>You won't need to set this, but if you see errors about the configured timeout of 100 seconds elapsing then you could set this to be more than 100 but I would recommend you just leave it to be `null`
