### ISSUE TITLE
OF DL V1.7.11 abruptly closes

### ISSUE THREAD

**Issue by Chrdvr** [sim0n00ps/OF-DL#42]
Latest seems to open, shows found directories and logged in as in console, then abruptly closes. Update as OF DL V1.7.10 started giving me the Exception caught.

**Comment by juddisjudd** [comment]
Also having this issue, .10 was also having the issue too though starting today.

**Comment by sim0n00ps** [comment]
Would help massively if you could maybe screen record what the exception is as you won't be able to see it after the window closes, it should of been fixed in the latest release, at least it was for me

**Comment by evilwadewilson** [comment]
Same issue, get this readout in powershell: 
Exception caught: Bad JSON escape sequence: \y. Path 'YTDLP_PATH', line 6, position 23.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program..ctor(APIHelper _aPIHelper, DownloadHelper _downloadHelper, DBHelper _dBHelper)
   at OF_DL.Program.Main()

**Comment by Chrdvr** [comment]
> Would help massively if you could maybe screen record what the exception is as you won't be able to see it after the window closes, it should of been fixed in the latest release, at least it was for me

I ran it through powershell and I get this:

Exception caught: The input string 'fans' was not in a correct format.

StackTrace:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at OF_DL.Helpers.APIHelper.GetLists(String endpoint)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.GetMainMenuOptions(Dictionary`2 users, Dictionary`2 lists)
   at OF_DL.Program.HandleUserSelection(Dictionary`2 selectedUsers, Dictionary`2 users, Dictionary`2 lists)
   at OF_DL.Program.Main()

**Comment by Chrdvr** [comment]
> > > Would help massively if you could maybe screen record what the exception is as you won't be able to see it after the window closes, it should of been fixed in the latest release, at least it was for me
> > 
> > 
> > I ran it through powershell and I get this:
> > Exception caught: The input string 'fans' was not in a correct format.
> > StackTrace: at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type) at OF_DL.Helpers.APIHelper.GetLists(String endpoint) Exception caught: Object reference not set to an instance of an object.
> > StackTrace: at OF_DL.Program.GetMainMenuOptions(Dictionary`2 users, Dictionary`2 lists) at OF_DL.Program.HandleUserSelection(Dictionary`2 selectedUsers, Dictionary`2 users, Dictionary`2 lists) at OF_DL.Program.Main()
> 
> Would you be able to check if you have a list called "fans"? I have managed to get the same issue but with a list called "following"

Yes I have the standard Fans list of who is following me and I have the standard Following list of who I am following.

**Comment by sim0n00ps** [comment]
> > > > Would help massively if you could maybe screen record what the exception is as you won't be able to see it after the window closes, it should of been fixed in the latest release, at least it was for me
> > > 
> > > 
> > > I ran it through powershell and I get this:
> > > Exception caught: The input string 'fans' was not in a correct format.
> > > StackTrace: at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type) at OF_DL.Helpers.APIHelper.GetLists(String endpoint) Exception caught: Object reference not set to an instance of an object. StackTrace: at OF_DL.Program.GetMainMenuOptions(Dictionary`2 users, Dictionary`2 lists) at OF_DL.Program.HandleUserSelection(Dictionary`2 selectedUsers, Dictionary`2 users, Dictionary`2 lists) at OF_DL.Program.Main()
> > 
> > 
> > Would you be able to check if you have a list called "fans"? I have managed to get the same issue but with a list called "following"
> 
> Yes I have the standard Fans list of who is following me and I have the standard Following list of who I am following.

Thanks for that, the issue is that the following and fans lists no longer have ids, they are separate endpoints on the API so will have to be excluded for now.

**Comment by sim0n00ps** [comment]
Just made the 1.7.12 release with the change, hopefully it will help

**Comment by Chrdvr** [comment]
> Just made the 1.7.12 release with the change, hopefully it will help

That works!
