### ISSUE TITLE
EXE won't open

### ISSUE THREAD

**Issue by em997nz** [sim0n00ps/OF-DL#424]
Hi there,

I was using OF.DL.V1.7.25 however am now trying to jump to OF.DL.V1.7.60.  I have followed the instructions for this latest version however when I click in the "OF DL.exe" in the new version, the application does not open.  I have added the application to the whilelist and disabled my firewall but still no luck.

Perhaps I installed the new version correctly?

**Comment by melithine** [comment]
Do you see any files in the log folder?

**Comment by em997nz** [comment]
Hi - there are no log files I can see. Where would they be located?

**Comment by melithine** [comment]
In a folder called `logs` under the directory where you have `OF DL.exe`. If you don't have that, try opening a PowerShell window, changing directories to where you have `OF DL.exe`, and running the exe directly. That will give you the output even if it has to exit.

**Comment by em997nz** [comment]
Thank you - I ran in PowerShell and this was the error message I got:

Exception caught: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

                                                                                                       StackTrace:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.Main()

**Comment by melithine** [comment]
Was there anything before the error, or just that?

**Comment by melithine** [comment]
And do you have `rules.json` in your ofdl directory?

**Comment by em997nz** [comment]
> Was there anything before the error, or just that?

No errors before:

 __        __         _                                       _                ___    _____           ____    _
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___      / _ \  |  ___|         |  _ \  | |
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \    | | | | | |_     _____  | | | | | |
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |   | |_| | |  _|   |_____| | |_| | | |___
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/     \___/  |_|             |____/  |_____|

yt-dlp.exe located successfully!
ffmpeg.exe located successfully!
mp4decrypt.exe located successfully!
device_client_id_blob located successfully!
device_private_key located successfully!
Exception caught: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by em997nz** [comment]
> And do you have `rules.json` in your ofdl directory?

Yes I do

**Comment by melithine** [comment]
That doesn't look like OF DL 1.7.60; we don't use yt-dlp.exe or mp4decrypt.exe anymore, just ffmpeg.exe. Try extracting the files from the zip again.

**Comment by em997nz** [comment]
> That doesn't look like OF DL 1.7.60; we don't use yt-dlp.exe or mp4decrypt.exe anymore, just ffmpeg.exe. Try extracting the files from the zip again.

You are correct - this is the error message with 1.7.60

 __        __         _                                       _                ___    _____           ____    _
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___      / _ \  |  ___|         |  _ \  | |
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \    | | | | | |_     _____  | | | | | |
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |   | |_| | |  _|   |_____| | |_| | | |___
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/     \___/  |_|             |____/  |_____|

Valid version of Windows found.
auth.json located successfully!
config.json located successfully!
FFmpeg located successfully
device_client_id_blob located successfully!
device_private_key located successfully!
Exception caught: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

                                                                                                       StackTrace:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)

**Comment by melithine** [comment]
Can you screenshot the directory?

**Comment by em997nz** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/173314768/57d10154-1774-4156-bce9-a8eb0ac1800d)

**Comment by melithine** [comment]
Try extracting the rules.json file from the zip again? It's before the normal "logged in as xyz" message but after validating config.json and auth.json, which leads me to think it's a problem with that file.

**Comment by melithine** [comment]
If that doesn't work, maybe one of the other folks will have a better idea. I wish c# stack traces showed line numbers :(

**Comment by melithine** [comment]
Were you able to get this solved?

**Comment by em997nz** [comment]
Sort of - clicking on the exe file doesn't work however I can operate through Powershell.  This suggests a firewall issue.

**Comment by em997nz** [comment]
config.json

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": null,
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": true,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "C:/Users/muse_/Downloads/Github/OF.DL.V1.7.60/ffmpeg.exe",
  "CreatorConfigs": {}
}

**Comment by em997nz** [comment]
rules.json

{
    "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "static_param": "RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y",
    "prefix": "24650",
    "suffix": "666078a0",
    "checksum_constant": 13,
    "checksum_indexes": [ 4, 5, 7, 9, 9, 11, 13, 17, 18, 19, 23, 23, 23, 24, 25, 26, 27, 27, 28, 28, 28, 28, 28, 29, 30, 32, 32, 33, 33, 34, 34, 38 ]
}
