### ISSUE TITLE
Docker execution receiving 404 and NullReferenceException

### ISSUE THREAD

**Issue by grid-wanderer** [sim0n00ps/OF-DL#425]
I've been getting a 404 HTTP response followed by a NRE (Object reference not set to an instance of an object):

> auth.json located successfully!
config.json located successfully!
FFmpeg located successfully
device_client_id_blob located successfully!
device_private_key located successfully!
Exception caught: Response status code does not indicate success: 404 (Not Found).
> 
> StackTrace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth) in /src/OF DL/Helpers/APIHelper.cs:line 50
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth) in /src/OF DL/Helpers/APIHelper.cs:line 95
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth) in /src/OF DL/Helpers/APIHelper.cs:line 205
Exception caught: Object reference not set to an instance of an object.
> 
> StackTrace:    at OF_DL.Program.Main(String[] args) in /src/OF DL/Program.cs:line 231

I first started getting this with 1.7.59 (after having not used it since 1.7.56 or so) and waited to see if 1.7.60 fixed it, but it has not. I did notice that the setup of `auth.json` had changed since I last used it and updated accordingly. I am running the docker version on linux.

Log file from my latest attempt is here if it helps: [OFDL20240620.txt](https://github.com/user-attachments/files/15908563/OFDL20240620.txt), although it seems to contain the same output as the stacktrace above.

**Comment by grid-wanderer** [comment]
Update on running - I've been following the [README](https://of-dl.gitbook.io/of-dl/install#running-via-docker) in regards to running the docker image, which specifies using `ghcr.io/sim0n00ps/of-dl:latest` as the target image. I changed this to `ghcr.io/sim0n00ps/of-dl:1.7.60` to make sure I was actually running 1.7.60 and I get a different error:

> Exception caught: Could not find file '/config/rules.json'.
> 
> StackTrace:
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func\`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func\`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable\`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams) in /src/OF DL/Helpers/APIHelper.cs:line 51
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint) in /src/OF DL/Helpers/APIHelper.cs:line 93
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint) in /src/OF DL/Helpers/APIHelper.cs:line 203

I've seen `rules.json` mentioned in issue #424, but I didn't see any information regarding that file in the README. What is the format/content of `rules.json` supposed to be?

**Comment by melithine** [comment]
https://raw.githubusercontent.com/sim0n00ps/OF-DL/master/OF%20DL/rules.json has a copy.

**Comment by grid-wanderer** [comment]
Perfect, things are working great now. Thank you!
