### ISSUE TITLE
SQLite Error 5: 'database is locked'

### ISSUE THREAD

**Issue by supernova4420** [sim0n00ps/OF-DL#432]
Hello, I am running the latest docker container (ubuntu hosted) version. After a successful log on, and starting a scrape, I get this error:

Exception caught: SQLite Error 5: 'database is locked'.

StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at OF_DL.Helpers.DBHelper.CreateDB(String folder) in /src/OF DL/Helpers/DBHelper.cs:line 34

Along with a fleet of subsequent 'no such table:' errors.

It might be worth noting that the media is stored on a NAS that I am connected to using /etc/fstab using this entry:

//192.168.1.2/media /media cifs credentials=/home/credentials,uid=1000,gid=1000,dir_mode=0777,file_mode=0777 0 0

**Comment by supernova4420** [comment]
After some research, adding the flag `nobrl' to my fstab entry resolved this issue.
