### ISSUE TITLE
unable to parse license

### ISSUE THREAD

**Issue by stanzel** [sim0n00ps/OF-DL#456]
I am getting unable to parse license errors on a couple of creators.  I'm on the latest build and have tried removing the metadata folder and redownloading. 

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-07-04 17:48:34.313 -04:00 [ERR] Exception caught: Unable to parse license

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-07-04 17:48:34.971 -04:00 [ERR] Exception caught: Unable to parse license

**Comment by stanzel** [comment]
deleted the entire folder for the creator, and it redownloaded without a problem
