### ISSUE TITLE
FEATURE REQUEST add creator name to log ifle

### ISSUE THREAD

**Issue by stanzel** [sim0n00ps/OF-DL#459]
add the creator name and file name to the log file

**Comment by melithine** [comment]
Can you elaborate?

**Comment by stanzel** [comment]
currently log file looks like:
```
StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-07-12 13:50:25.780 -04:00 [ERR] Exception caught: Unable to parse license

```
i would like something like this:
```
StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-07-12 13:50:25.780 -04:00 [ERR] Exception caught: Unable to parse license
**CREATOR: <<creator name>>  filename: <<filename>> **
```
or something like it

**Comment by melithine** [comment]
I know @thatcoderguy made a bunch,of logging changes recently, so,please check and see if that info was included in 1.7.67, otherwise it seems simple enough to add,in the future.
