### ISSUE TITLE
FFmpeg failed to download  Exception caught: Could not find file 

### ISSUE THREAD

**Issue by oppppppay** [sim0n00ps/OF-DL#466]
I can only download photos but not videos. How can I solve this problem? Please help me. All are already the latest version

FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/d/de/de671313d63ebbb8553ef83922d3def9/0ho4atqwrhddb3j6332ua.mpd
Exception caught: Could not find file 'E:\OF\of1\jiniphee\Posts\Free\Videos\0ho4atqwrhddb3j6332ua_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                                                   pe, ProgressTask task, String filename
   
   
![image](https://github.com/sim0n00ps/OF-DL/assets/146720706/1670eb2d-bce8-4b9c-b44b-a3f09c2cb95a)

**Comment by kaine1973** [comment]
Same here, don't know how to solve this problem.
<img width="1218" alt="截屏2024-07-15 16 57 46" src="https://github.com/user-attachments/assets/bbc3caa3-8875-400e-bba8-592041264a73">

**Comment by melithine** [comment]
Can you upgrade to the new release, change logging level to debug or verbose, and attach the log file?

**Comment by kaine1973** [comment]
> Can you upgrade to the new release, change logging level to debug or verbose, and attach the log file?
I changed loglevel to verbose. you can check the log:
[OFDL20240715.txt](https://github.com/user-attachments/files/16232330/OFDL20240715.txt)

**Comment by melithine** [comment]
This seems to be an access denied issue:
```
2024-07-15 17:06:52.510 +08:00 [ERR] ffmpeg version 6.1.1-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
...
[Snipped ffmpeg compilation details]
...
[https @ 000002f0524acd80] HTTP error 403 Forbidden
[in#0 @ 000002f0524ac640] Error opening input: Server returned 403 Forbidden (access denied)
Error opening input file https://cdn3.onlyfans.com/dash/files/1/1c/1c1d14c4b18885bf532c0485beb57615/0hen3egn05uf5w5vnmvv4.mpd.
Error opening input files: Server returned 403 Forbidden (access denied)

2024-07-15 17:06:52.511 +08:00 [ERR] Exception caught: Could not find file 'F:\OFDL\danielmoura\Posts\Free\Videos\0hen3egn05uf5w5vnmvv4_source.mp4'.
```
It can't find the file because ffmpeg got a 403 when requesting the DASH file from OnlyFans. We've seen this behavior before, but it was always unclear what was causing it. Hopefully the new logs will be able to shed further light on the cause of the issue. Tagging @sim0n00ps to take a look when he has some time.

**Comment by sim0n00ps** [comment]
I think we need to revisit where it generates the headers it passes to ffmpeg as 403 would indicate that the session info is malformed/incorrect

**Comment by banjobbw** [comment]
Having the same issue

```
dash/files/8/84/84f9fd016fc827a8ab550a2bca389901/0hmgb282we2ssvod43ua1.mpd
Exception caught: Could not find file 'Z:\111111111111111111111111\OFDLV1.7.68\__user_data__\sites\OnlyFans\dulcenalgass\Posts\Free\Videos\0hmgb282we2ssvod43ua1_source.mp4'.

                                                     StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                                      String api_type, ProgressTask task, String filename
Downloading 2741 Posts ----------------------------------------   4% users)
```

**Comment by melithine** [comment]
I consolidated all the various related issues into this thread so we can keep better track of it.

**Comment by twist3dimages** [comment]
Same error message with Verbose and Debug 
<img width="1913" alt="image" src="https://github.com/user-attachments/assets/e2c2f379-1b6c-4a1b-ace5-7b6308d32616">

**Comment by whoisty14** [comment]
I get this code based off the VPN location that I use

**Comment by sim0n00ps** [comment]
> Same error message with Verbose and Debug 
> 
> Verbose: 
> <img width="1913" alt="image" src="https://github.com/user-attachments/assets/e2c2f379-1b6c-4a1b-ace5-7b6308d32616">
> 
> Debug:
> 
> <img width="1910" alt="image" src="https://github.com/user-attachments/assets/49c70d5f-fa24-4ca8-8646-61d673388633">
> 

Are you able to upload the log file, it should be in the logs folder

**Comment by twist3dimages** [comment]
[OFDL20240809.zip](https://github.com/user-attachments/files/16570567/OFDL20240809.zip)


Weirdly, i saw someone's comment about using a VPN. I was able to download the posts with no problem when I wasn't using a VPN.

**Comment by melithine** [comment]
Onlyfans blocks some VPNs, so there's not much we can do about that.

**Comment by melithine** [comment]
Another thought for people affected by this... Try installing Docker Desktop from https://www.docker.com/products/docker-desktop/ and start it up.

Then open a Powershell window and run it like so: `docker run -it -v /f/onlyfans/data/:/data -v /f/onlyfans/config/:/config ghcr.io/sim0n00ps/of-dl:latest`

Adjust /f/onlyfans/config and /f/onlyfans/data to wherever you're storing the files. Mine are in F:/onlyfans/, so make sure the path is using forward slashes and you're not using a colon after the drive letter. The config folder should be wherever you have `auth.json` and the `cdm` directory, the data folder is wherever you want the files saved.

I'm curious if you still see the 403 issues under Docker.

**Comment by dagr8boy** [comment]
I wanted to add some context since I created #518. For me it looks like it's just one post from one creator that has DRM enabled; None of the recent posts from another creator that has DRM enabled caused this issue. I think if you added some error handling for individual posts/messages and not cause the app to exit, users could skip the offending item and move along.

**Comment by bezaaas** [comment]
I've noticed that on next runs, the script downloads these files without any issues.

**Comment by Smackdab69** [comment]
I see some references to "DRM" here, I assume the offending videos have some additional protection hence why they're failing?

**Comment by twist3dimages** [comment]
> Another thought for people affected by this... Try installing Docker Desktop from https://www.docker.com/products/docker-desktop/ and start it up.
> 
> Then open a Powershell window and run it like so: `docker run -it -v /f/onlyfans/data/:/data -v /f/onlyfans/config/:/config ghcr.io/sim0n00ps/of-dl:latest`
> 
> Adjust /f/onlyfans/config and /f/onlyfans/data to wherever you're storing the files. Mine are in F:/onlyfans/, so make sure the path is using forward slashes and you're not using a colon after the drive letter. The config folder should be wherever you have `auth.json` and the `cdm` directory, the data folder is wherever you want the files saved.
> 
> I'm curious if you still see the 403 issues under Docker.

Do you still want me to try? And do you want me to still be on the VPN?

**Comment by twist3dimages** [comment]
> I see some references to "DRM" here, I assume the offending videos have some additional protection hence why they're failing?

I have no issues with DRM personally. Just a few posts from one model

**Comment by melithine** [comment]
Thanks, folks. We're still not sure exactly what's causing this, but we're going to refactor this section of code to address the problems that are going on and add better logging around it as well. Further logs are not needed at this time, so I'm going to lock the thread but leave it open until we have the refactor completed.

**Comment by melithine** [comment]
Unlocking this. Version 1.7.75 has been released with refactors how ffmpeg is handled, so people who have been affected by this issue should update and test it out. Hopefully this helps you all! And as a side note, it will also tell you at startup if there is a newer version available, so you don't have to keep as close an eye on the Discord server or release notifications through GitHub.

**Comment by Joe-lol** [comment]
[OFDL20240904.txt](https://github.com/user-attachments/files/16882555/OFDL20240904.txt)

Here is a log with the latest version.

**Comment by Higgis39** [comment]
I still cannot download drm videos, logs:

```
2024-09-05 20:57:36.227 +08:00 [ERR] Exception caught: ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[https @ 000001b475810d80] No trailing CRLF found in HTTP header. Adding it.
[https @ 000001b475810d80] HTTP error 403 Forbidden
[in#0 @ 000001b475813c00] Error opening input: Server returned 403 Forbidden (access denied)
Error opening input file https://cdn3.onlyfans.com/dash/files/***/***/***/***.mpd.
Error opening input files: Server returned 403 Forbidden (access denied)

StackTrace:    at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass14_0.<RunProcess>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Xabe.FFmpeg.Conversion.Start(String parameters, CancellationToken cancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
```

**Comment by wireman21** [comment]
I had this issue, and the error message told me to add ffmpeg to PATH. I added "C:\Users\username\Downloads\OFDLV1.7.75\ffmpeg.exe" (depends on your location) to PATH in Enviroment Variables in System Properties.

So far things look good.

**Comment by oppppppay** [comment]
> 您能升级到新版本、将日志记录级别更改为调试或详细、并附加日志文件吗？

> 2024-09-20 00:38:41.366 +08:00 [ERR] Cannot locate FFmpeg with path: 
2024-09-20 00:45:17.097 +08:00 [ERR] Cannot locate FFmpeg with path: 
2024-09-20 01:25:26.722 +08:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetLists(String endpoint, IDownloadConfig config)
2024-09-20 01:25:26.749 +08:00 [ERR] Inner Exception: Received an unexpected EOF or 0 bytes from the transport stream.

StackTrace:    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2024-09-20 01:25:26.795 +08:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.GetMainMenuOptions(Dictionary`2 users, Dictionary`2 lists)
   at OF_DL.Program.HandleUserSelection(APIHelper apiHelper, Config currentConfig, Dictionary`2 users, Dictionary`2 lists)
   at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config)
   at OF_DL.Program.Main(String[] args)
2024-09-20 01:31:49.120 +08:00 [ERR] Exception caught: Could not find file 'C:\Users\xinmi\Desktop\OF xin\__user_data__\sites\OnlyFans\triplexceleste\Posts\Free\Videos\0hs6kh3jc0xfp4kow23ck_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
2024-09-20 01:31:57.294 +08:00 [ERR] Exception caught: Could not find file 'C:\Users\xinmi\Desktop\OF xin\__user_data__\sites\OnlyFans\triplexceleste\Posts\Free\Videos\0hrty9fxw86djmogdbpk9_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
2024-09-20 01:32:11.980 +08:00 [ERR] Exception caught: Could not find file 'C:\Users\xinmi\Desktop\OF xin\__user_data__\sites\OnlyFans\triplexceleste\Posts\Free\Videos\0hsu4fx90ziiruj0hqsdu_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
2024-09-20 01:32:44.171 +08:00 [ERR] Exception caught: Could not find file 'C:\Users\xinmi\Desktop\OF xin\__user_data__\sites\OnlyFans\triplexceleste\Posts\Free\Videos\0hsu4fvacn6po8tv75bx6_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String c

**Comment by oppppppay** [comment]
> > 您可以升级到新版本、将日志记录级别更改为调试或详细、并附加日志文件吗？
> 
> [OFDL20240920.txt](https://github.com/user-attachments/files/17063710/OFDL20240920.txt)


I've upgraded to the latest version, but what the heck caused this? Thanks for your help!
