### ISSUE TITLE
1.767: SQLite Handling Broken (Exception caught: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.)

### ISSUE THREAD

**Issue by ViRGEdx** [sim0n00ps/OF-DL#471]
It would seem that 1.7.67 didn't make it out without picking up a new bug in the process.

Running the client with both existing and fresh configs is producing the following error all over the place.

```
Exception caught: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
StackTrace:    at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at OF_DL.Helpers.DBHelper.CreateUsersDB(Dictionary`2 users)

Inner Exception:
Exception caught: Exception has been thrown by the target of an invocation.
StackTrace:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
```

It looks like SQLite handling is broken, so that error is being generated every time OF-DL wants to read or write from a DB file. And sure enough, no DB files are being created/updated after running the client, confirming that the writes aren't going through.

Turning on Verbose logging (neat feature!) isn't showing anything else of use.

**Comment by sim0n00ps** [comment]
Re-copy "e_sqlite3.dll" from the release ZIP file and copy it to where you have OF DL.exe and overwrite the old one

**Comment by ViRGEdx** [comment]
Yep, that was it. Thanks!

I hadn't bothered copying it over, since it has the same modified date as the previous version.
