### ISSUE TITLE
Exception caught error

### ISSUE THREAD

**Issue by samwant89** [sim0n00ps/OF-DL#508]
I've got this error after setting up everything.. Its a little bit delay before this error appear.

```
2024-08-05 22:07:27.232 +08:00 [ERR] Exception caught: The format of value 'Safari/537.36
' is invalid.

StackTrace:    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-05 22:07:27.273 +08:00 [ERR] Auth failed
2024-08-05 22:09:38.547 +08:00 [ERR] Exception caught: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

StackTrace:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-05 22:09:38.733 +08:00 [ERR] Inner Exception: A task was canceled.

StackTrace: null
2024-08-05 22:09:38.758 +08:00 [ERR] Auth failed
```

**Comment by melithine** [comment]
You have a trailing newline on the `USER_AGENT` line of `auth.json`. It should look like:
```
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
```
and not like:
```
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
",
```

**Comment by samwant89** [comment]
> You have a trailing newline on the `USER_AGENT` line of `auth.json`. It should look like:
> 
> ```
>   "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
> ```
> 
> and not like:
> 
> ```
>   "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
> ",
> ```

I've got another error and still cannot get through
```
2024-08-06 09:48:54.131 +08:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.


StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-06 09:48:54.171 +08:00 [ERR] Inner Exception: The remote certificate is invalid because of errors in the certificate chain: PartialChain

StackTrace:    at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2024-08-06 09:48:54.174 +08:00 [ERR] Auth failed
2024-08-06 09:51:19.391 +08:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-06 09:51:19.428 +08:00 [ERR] Inner Exception: The remote certificate is invalid because of errors in the certificate chain: PartialChain

StackTrace:    at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2024-08-06 09:51:19.432 +08:00 [ERR] Auth failed
2024-08-06 12:38:57.925 +08:00 [ERR] Exception caught: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

StackTrace:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-06 12:38:57.981 +08:00 [ERR] Inner Exception: A task was canceled.

StackTrace: null
2024-08-06 12:38:57.985 +08:00 [ERR] Auth failed
```

**Comment by melithine** [comment]
That's some form of networking problem between you and onlyfans. Could be a proxy server blocking the connection, or your country doesn't allow onlyfans, or something else. If you're using a VPN, try directly or a different vpn location. If you're not using one currently, try using one.

**Comment by samwant89** [comment]
> That's some form of networking problem between you and onlyfans. Could be a proxy server blocking the connection, or your country doesn't allow onlyfans, or something else. If you're using a VPN, try directly or a different vpn location. If you're not using one currently, try using one.

I solve the vpn part and now i can get through. but theres another error appear..

`
2024-08-07 13:56:01.223 +08:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)
2024-08-07 13:58:07.648 +08:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

`

**Comment by samwant89** [comment]
> That's some form of networking problem between you and onlyfans. Could be a proxy server blocking the connection, or your country doesn't allow onlyfans, or something else. If you're using a VPN, try directly or a different vpn location. If you're not using one currently, try using one.

I solved the vpn part and now i can get through.. but there was another error..

```
2024-08-07 13:56:01.223 +08:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)
2024-08-07 13:58:07.648 +08:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).
```
