### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by jrhenry** [sim0n00ps/OF-DL#511]
Hi! I've not been able to get this to authenticate. I even used the browser extension to get the auth.json file information and cleared my cache but still no luck. Any help is appreciated. Thank you! 
<img width="863" alt="image" src="https://github.com/user-attachments/assets/593298af-7973-4b1d-9bca-2b4e6dfb64c8">

**Comment by jrhenry** [comment]
Here's my auth.json. Am I missing something? I appreciate any and all help!
<img width="800" alt="image" src="https://github.com/user-attachments/assets/8c5cd551-234e-43f9-b297-f80c3d2be3cb">

**Comment by melithine** [comment]
I'd try using the browser extension again; that all looks good, but if you're still stuck, change the logging level in config.json and send it to us, it's not really showing any red flags so we'd need the deep dive info that the logs can provide.

**Comment by jrhenry** [comment]
Thank you, unfortunately it barfed again. Is this what you're looking for?

2024-08-13 19:43:30.108 -04:00 [DBG] Configuration:
2024-08-13 19:43:30.166 -04:00 [DBG] {
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": -1,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "before",
  "CustomDate": null,
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "C:/Users/james/Documents/OF-DL/ffmpeg.exe",
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "CreatorConfigs": {},
  "DownloadDuplicatedMedia": false,
  "IgnoredUsersListName": "",
  "LoggingLevel": "Debug"
}
2024-08-13 19:43:30.167 -04:00 [DBG] Operating system information: Microsoft Windows NT 10.0.22631.0
2024-08-13 19:43:30.169 -04:00 [DBG] Auth file found and deserialized
2024-08-13 19:43:30.175 -04:00 [DBG] Rules.json: 
2024-08-13 19:43:30.175 -04:00 [DBG] "{\n    \"app-token\": \"33d57ade8c02dbc5a333db99ff9ae26a\",\n    \"static_param\": \"RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y\",\n    \"prefix\": \"24650\",\n    \"suffix\": \"666078a0\",\n    \"checksum_constant\": 13,\n    \"checksum_indexes\": [ 4, 5, 7, 9, 9, 11, 13, 17, 18, 19, 23, 23, 23, 24, 25, 26, 27, 27, 28, 28, 28, 28, 28, 29, 30, 32, 32, 33, 33, 34, 34, 38 ]\n}\n"
2024-08-13 19:43:30.176 -04:00 [DBG] FFMPEG found: C:/Users/james/Documents/OF-DL/ffmpeg.exe
2024-08-13 19:43:30.176 -04:00 [DBG] FFMPEG path set in config.json
2024-08-13 19:43:30.176 -04:00 [DBG] clientIdBlobMissing missing
2024-08-13 19:43:30.176 -04:00 [DBG] devicePrivateKeyMissing missing
2024-08-13 19:43:30.178 -04:00 [DBG] Calling GetUserInfo: /users/me
2024-08-13 19:43:30.189 -04:00 [DBG] Calling BuildHttpRequestMessage
2024-08-13 19:43:30.191 -04:00 [DBG] Calling GetDynamicHeaders
2024-08-13 19:43:30.191 -04:00 [DBG] Path: /api2/v2/users/me
2024-08-13 19:43:30.191 -04:00 [DBG] Query Params: ?limit=50&order=publish_date_asc
2024-08-13 19:43:30.200 -04:00 [DBG] Full request URL: https://onlyfans.com/api2/v2/users/me?limit=50&order=publish_date_asc
2024-08-13 19:43:30.417 -04:00 [ERR] Auth failed

**Comment by melithine** [comment]
Yeah, though that doesn't really have enough info, like what reply it got back from OF, just that it didn't work. Looks like we need to add more detail to that section of logging (although not too much, for security's sake). Your rules.json does look correct at least.

When you fail to auth with OFDL, is your browser session getting logged out, too? It should, typically; if it's not, that indicates it wasn't able to succeed far enough for them to associate it with your browser session and thus invalidate it.

**Comment by jrhenry** [comment]
Yes, my browser is getting logged out so that's something at least. Is there anything else I should try at this point? Thank you for all the help!

**Comment by jaimeand78** [comment]
i have the same issue

2024-08-27 14:04:36.375 -05:00 [DBG] Operating system information: Microsoft Windows NT 10.0.22631.0
2024-08-27 14:04:36.377 -05:00 [DBG] Auth file found and deserialized
2024-08-27 14:04:36.381 -05:00 [DBG] Rules.json: 
2024-08-27 14:04:36.382 -05:00 [DBG] "{\n    \"app-token\": \"33d57ade8c02dbc5a333db99ff9ae26a\",\n    \"static_param\": \"RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y\",\n    \"prefix\": \"24650\",\n    \"suffix\": \"666078a0\",\n    \"checksum_constant\": 13,\n    \"checksum_indexes\": [ 4, 5, 7, 9, 9, 11, 13, 17, 18, 19, 23, 23, 23, 24, 25, 26, 27, 27, 28, 28, 28, 28, 28, 29, 30, 32, 32, 33, 33, 34, 34, 38 ]\n}\n"
2024-08-27 14:04:36.383 -05:00 [DBG] FFMPEG found: ****/OFDLV1.7.73/ffmpeg.exe
2024-08-27 14:04:36.383 -05:00 [DBG] FFMPEG path set in config.json
2024-08-27 14:04:36.383 -05:00 [DBG] clientIdBlobMissing missing
2024-08-27 14:04:36.383 -05:00 [DBG] devicePrivateKeyMissing missing
2024-08-27 14:04:36.384 -05:00 [DBG] Calling GetUserInfo: /users/me
2024-08-27 14:04:36.390 -05:00 [DBG] Calling BuildHttpRequestMessage
2024-08-27 14:04:36.391 -05:00 [DBG] Calling GetDynamicHeaders
2024-08-27 14:04:36.391 -05:00 [DBG] Path: /api2/v2/users/me
2024-08-27 14:04:36.391 -05:00 [DBG] Query Params: ?limit=50&order=publish_date_asc
2024-08-27 14:04:36.397 -05:00 [DBG] Full request URL: https://onlyfans.com/api2/v2/users/me?limit=50&order=publish_date_asc
2024-08-27 14:04:36.746 -05:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-08-27 14:04:36.751 -05:00 [ERR] Inner Exception: The remote certificate is invalid because of errors in the certificate chain: PartialChain

StackTrace:    at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2024-08-27 14:04:36.755 -05:00 [ERR] Auth failed

**Comment by crashsc** [comment]
I began having this same problem two days ago after I rebooted my computer (I don't do that as often as I should). Fails to authenticate and logs me out on my browser.

2024-09-06 16:48:21.764 -04:00 [DBG] Configuration:
2024-09-06 16:48:21.827 -04:00 [DBG] {
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 20,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": null,
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "",
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "CreatorConfigs": {},
  "DownloadDuplicatedMedia": false,
  "IgnoredUsersListName": "",
  "LoggingLevel": "Debug"
}
2024-09-06 16:48:21.827 -04:00 [DBG] Operating system information: Microsoft Windows NT 10.0.19043.0
2024-09-06 16:48:22.569 -04:00 [DBG] Detected client running version 1.7.75
2024-09-06 16:48:22.569 -04:00 [DBG] Latest GitHub release version 1.7.75
2024-09-06 16:48:22.572 -04:00 [DBG] Auth file found and deserialized
2024-09-06 16:48:22.578 -04:00 [DBG] Rules.json: 
2024-09-06 16:48:22.578 -04:00 [DBG] "{\n    \"app-token\": \"33d57ade8c02dbc5a333db99ff9ae26a\",\n    \"static_param\": \"RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y\",\n    \"prefix\": \"24650\",\n    \"suffix\": \"666078a0\",\n    \"checksum_constant\": 13,\n    \"checksum_indexes\": [ 4, 5, 7, 9, 9, 11, 13, 17, 18, 19, 23, 23, 23, 24, 25, 26, 27, 27, 28, 28, 28, 28, 28, 29, 30, 32, 32, 33, 33, 34, 34, 38 ]\n}\n"
2024-09-06 16:48:22.581 -04:00 [DBG] FFMPEG found: H:\OF-DL 1.7.75\ffmpeg.exe
2024-09-06 16:48:22.581 -04:00 [DBG] FFMPEG path found in windows excutable directory
2024-09-06 16:48:22.581 -04:00 [DBG] clientIdBlobMissing missing
2024-09-06 16:48:22.581 -04:00 [DBG] devicePrivateKeyMissing missing
2024-09-06 16:48:22.583 -04:00 [DBG] Calling GetUserInfo: /users/me
2024-09-06 16:48:22.585 -04:00 [DBG] Calling BuildHttpRequestMessage
2024-09-06 16:48:22.587 -04:00 [DBG] Calling GetDynamicHeaders
2024-09-06 16:48:22.587 -04:00 [DBG] Path: /api2/v2/users/me
2024-09-06 16:48:22.587 -04:00 [DBG] Query Params: ?limit=50&order=publish_date_asc
2024-09-06 16:48:22.592 -04:00 [DBG] Full request URL: https://onlyfans.com/api2/v2/users/me?limit=50&order=publish_date_asc
2024-09-06 16:48:22.721 -04:00 [ERR] Auth failed

**Comment by crashsc** [comment]
Update - I was able to successfully use OF-DL with Firefox.
