### ISSUE TITLE
Getting "Found 0 paid posts"

### ISSUE THREAD

**Issue by GITHU8HO** [sim0n00ps/OF-DL#513]
Content bought today or even several months ago not showing up under paid posts.

Version: 1.7.71
config.json located successfully!
Valid version of Windows found.
auth.json located successfully!
rules.json located successfully!
FFmpeg located successfully

**Comment by thatcoderguy** [comment]
Can you post a copy of your config?

**Comment by GITHU8HO** [comment]
Sure

"{
  "DownloadAvatarHeaderPhoto": false,
  "DownloadPaidPosts": true,
  "DownloadPosts": false,
  "DownloadArchived": false,
  "DownloadStreams": false,
  "DownloadStories": false,
  "DownloadHighlights": false,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": false,
  "DownloadVideos": false,
  "DownloadAudios": false,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "FFmpegPath": "C:/Users/LGPCM/Downloads/ffmpeg-7.0-essentials_build/ffmpeg-7.0-essentials_build/bin/ffmpeg.exe",
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
}"

**Comment by thatcoderguy** [comment]
set these both to true

"DownloadImages": false,
"DownloadVideos": false,

**Comment by GITHU8HO** [comment]
Getting a whole lot of this, upon enabling "true" for DOwnloadImages & DownloadVideos

  Exception caught: The SSL connection could not be established, see inner exception.

                                                                                                                                                        StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: Received an unexpected EOF or 0 bytes from the transport stream.

                                                                                  StackTrace:    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
                                                                     icy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String filenameFormat, Li

**Comment by GITHU8HO** [comment]
How do I do that

**Comment by thatcoderguy** [comment]
In the main menu there's a option to change the logging level

**Comment by thatcoderguy** [comment]
Are you using a VPN?

**Comment by GITHU8HO** [comment]
Yes, always have.

**Comment by GITHU8HO** [comment]
Should I disable it

**Comment by GITHU8HO** [comment]
No joy. Still same issues. I'm going to try a new install

**Comment by GITHU8HO** [comment]
The fresh install did it. Think copy pasting auth and config data from older version OF DL might have been the issue.
