### ISSUE TITLE
Exception caught: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by samwant89** [sim0n00ps/OF-DL#519]
Previously I can download successfully. But suddenly this error came out. I'm currently using vpn.
To add : I have no problem playing videos from OF. Any suggestion?
Error:
```
Downloading Post ----------------------------------------   0%
                                                              Exception caught: The SSL connection could not be established, see inner exception.

                         StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: Received an unexpected EOF or 0 bytes from the transport stream.

                                                                                  StackTrace:    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
                                                              c(SslClientAuthenticationOptions sslOptions, HttpRequestMeDownloading Post ----------------------------------------   0% cancellationToken)
                                                              Exception caught: Object reference not set to an instance of an object.

             StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                               ia_id, String api_type, ProgressTask task, String filenameDownloading Post ----------------------------------------   0%Dictionary`2 users)
```

**Comment by melithine** [comment]
I'm assuming you don't have your own Widevine keys and are using cdrm-project, which is (once again) having issues.

**Comment by samwant89** [comment]
So i guess, its not a network problem. But i can use OFDL for only 3 days, after that its suddenly error..

**Comment by melithine** [comment]
If you're on Discord, I can send you a set of Widevine keys, just see my message in `#general` and DM me for the zip.

**Comment by samwant89** [comment]
yes, i have discord
