### ISSUE TITLE
OFDL not working now

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#527]
2024-08-20 16:43:35.575 +00:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 16:43:36.791 +00:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)

**Comment by CorpseBloom** [comment]
Having this same issue, or similar.

**Comment by melithine** [comment]
Duplicate of #523
