### ISSUE TITLE
Error downloading any file (not the first time I try your work, good job!)

### ISSUE THREAD

**Issue by jretro4** [sim0n00ps/OF-DL#529]
![image](https://github.com/user-attachments/assets/ce7b43a3-32f9-4b94-82c8-f71580c5ba5c)

Until a while ago everything was going well until it stopped working.

Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)

**Comment by nachoman91** [comment]
I have exactly the same issue, from log file:

2024-08-20 21:22:27.628 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 21:22:28.461 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 21:22:29.261 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 21:25:34.245 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 21:25:34.953 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetArchived(String endpoint, String folder, IDownloadConfig config)
2024-08-20 21:25:35.654 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder, IDownloadConfig config, List`1 paid_post_ids)
2024-08-20 21:27:26.922 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)

**Comment by sim0n00ps** [comment]
Already aware please don't open more issues please use #523
