### ISSUE TITLE
Cound Not Find File

### ISSUE THREAD

**Issue by digitalwiz** [sim0n00ps/OF-DL#54]
Got this error 6 times on 873 Posts and 22 times on 36 Messages

Downloading 873 Posts ----------------------------------------   0% 0.0/220.4 GB --:--:--
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0hf6nugmb8ckw2aqsviz9_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder

Tried running twice same errors.

**Comment by digitalwiz** [comment]
All errors on second run.

Downloading 873 Posts ----------------------------------------   0% 0.0/220.4 GB --:--:--
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0hf6nugmb8ckw2aqsviz9_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 873 Posts ----------------------------------------   0% 0.0/220.4 GB --:--:--
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0heyc47p1xu8idpdpingu_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 873 Posts ----------------------------------------   1% 2.4/220.4 GB 00:06:01
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0hea0td67gpu635nw1mt4_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 873 Posts ----------------------------------------   1% 2.4/220.4 GB 00:06:01
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0he0as22ih4mvp62muzb3_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 873 Posts ----------------------------------------   1% 2.4/220.4 GB 00:06:01
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0he0af140mbdrrz4uduc3_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 873 Posts ----------------------------------------   1% 2.4/220.4 GB 00:06:01
                                                                                         Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0hdpsw45fi6dqkh2ud748_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                            decryptionKey, String folder
Downloading 873 Posts ----------------------------------------  98% 220.4 GB 00:00:00


Downloading 36 Messages ----------------------------------------   0% 0.0/16.3 GB --:--:--
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hf281zybmxja4oo57q4o_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:01:07
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0heyeslyijx97nd10xcny_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:01:20
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0heu7o41sfol69czimkdd_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:01:33
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdy9z4zcwehz5n6b4cr4_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:01:52
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0heyb7i63x19jlith85y1_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:02:05
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hebalje4rrnojatdh48z_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:02:22
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hen3nrkikye3dfrl8g1m_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------   4% 0.8/16.3 GB 00:02:35
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hejddx5vwlt60ara1tb0_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:01:35
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0he69l5mog1qkk0vz7qu8_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:01:43
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0he7cyekjh3l7p2cvs8n9_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:01:49
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0he56nrziue3fdc3sdffw_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:01:54
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdpa2iy527s16isda7ri_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:02:09
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdwitrg2g9b9xfl3vasv_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:02:36
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdm3beookktfeavgytxj_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:02:44
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdu5dbxryberxp43d4gl_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:02:52
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdt9qq5qsz5op8itewr4_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:03:01
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdl2zqowddeunawxxzil_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:03:06
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0he0aq216yf83b417ba9w_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:03:11
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdub4kggrtqw4xi6qrik_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  11% 1.9/16.3 GB 00:03:52
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdpssu9s72lcvuorjnez_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  25% 4.2/16.3 GB 00:01:19
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdks0vbc5mnycy9ovh17_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  25% 4.2/16.3 GB 00:01:21
                                                                                          Exception caught: Could not find file 'F:\OF\__user_data__\sites\OnlyFans\emily_valentina\Messages\Free\Videos\0hdjhnuzqfk1f366ga863_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, S                                                                                          ring decryptionKey, String fol
Downloading 36 Messages ----------------------------------------  75% 16.3 GB 00:00:00

**Comment by sim0n00ps** [comment]
What paths have you got in your auth.json and what exe files have you downloaded?

**Comment by digitalwiz** [comment]
> Try delete the "Metadata" folder under "OF DL_user_data_\sites\OnlyFans[the creator's account name]" then re-running the program.

I tried deleting the "Metadata" and got the same result.

**Comment by digitalwiz** [comment]
> What paths have you got in your auth.json and what exe files have you downloaded?

Everything is in the same folder.

OF.DL.V1.7.12.zip
Bento4-SDK-1-6-0-640.x86_64-microsoft-win32.zip
ffmpeg-6.0-essentials_build.7z
yt-dlp_win.zip

I think I downloaded the latest versions of all files.
I am on Windows 11

This is the paths

"YTDLP_PATH": "F:/OF/yt-dlp.exe",
"FFMPEG_PATH": "F:/OF/ffmpeg.exe",
"MP4DECRYPT_PATH": "F:/OF/mp4decrypt.exe",

**Comment by digitalwiz** [comment]
yt-dlp_win.zip

Name           Size              Packed        Modified      CRC32
yt-dlp.exe     5,707,346     5,562,485    6/27/2023    25C31CDC

**Comment by digitalwiz** [comment]
Changed to build yt-dlp 2023.06.22
It is working with no errors.

Thank you for your help
