### ISSUE TITLE
1.7.74 FFMPEG errors

### ISSUE THREAD

**Issue by Smackdab69** [sim0n00ps/OF-DL#541]
Seeing the following errors when trying to download some videos from OF:

FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/d/d7/d700e44ba61ed3ec8710f0c4b4c9b69e/0hqf3a9u2jhiqi6t7ujke.mpd
Exception caught: Could not find file 'S:\___OnlyFans Ripping\OFDLV1.7.74\__user_data__\sites\OnlyFans\creator\Posts\Free\Videos\filename_source.mp4'.

                                                     StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, Stri

**Comment by melithine** [comment]
Can you capture this with the logging level set to debug/verbose? The base exception isn't detailed enough.

**Comment by Smackdab69** [comment]
Sure can, but how do I do that?

**Comment by melithine** [comment]
Launch the app, select change logging level, select verbose, then retry the behavior that failed. Upload the resulting log file.

**Comment by lexus033** [comment]
The same thing happens to me and I already put the solution they said but it doesn't fix it :(

**Comment by DonaldTPP** [comment]
I get this message:

FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/3/3f/3f52a1fb53da397fef55d4cf31bc08f8/0ht1414p9fc4qbwhghrr8.mpd
Exception caught: Could not find file 'D:\OFDL1.7.74\__user_data__\sites\OnlyFans\<redactedusername>\Messages\Free\Videos\0ht1414p9fc4qbwhghrr8_source.mp4'.

                                  StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String policy, String signature, String kvp, String url, Stri                                                                    id, String api_type, ProgressTask task, String filen
Downloading 1 Messages ----------------------------------------   0% Dictionary`2 users)

**Comment by melithine** [comment]
Stacktraces don't really help, debug logs are needed here.

**Comment by reqname** [comment]
I was having the same issue. I am on the newest version of FFMPEG using cdrm-project. Weirdly when I turned on verbose logging it seems to no longer happen. Will post a log if it happens again.

**Comment by Crisped2225** [comment]
Date: Wed, 28 Aug 2024 01:59:37 GMT
  Connection: keep-alive
  Server: Werkzeug/3.0.3 Python/3.10.12
  Content-Type: application/json
  Content-Length: 5811
}
2024-08-27 21:59:37.451 -04:00 [ERR] ffmpeg version 7.0.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Unrecognized option '->\n\n\n'.
Error splitting the argument list: Option not found

2024-08-27 21:59:37.452 -04:00 [ERR] Exception caught: Could not find file 'Z:\OFDL\__user_data__\sites\OnlyFans\<name>\Posts\Free\Videos\0ho07avrjpjcb9psr4vzg_source.mp4'.

StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users)

**Comment by reqname** [comment]
Same issue as user above with same error message. It seems to do it randomly even when downloading the same file.

**Comment by DonaldTPP** [comment]
Can confirm that this is happening with people with DRM protection active. Scraped two separate users after deleting their content. DRM active had the same error as the other non DRM user finished fine.

**Comment by DonaldTPP** [comment]
> Stacktraces don't really help, debug logs are needed here.

[ERR] Exception caught: Could not find file 'D:\OFDL1.7.74\__user_data__\sites\OnlyFans\<profilename>\Posts\Free\Videos\0hj374ltvdoay42zh94u7_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users)
2024-09-01 17:09:34.402 +10:00 [DBG] Calling GetDRMMPDLastModified
2024-09-01 17:09:34.402 +10:00 [DBG] mpdUrl: https://cdn3.onlyfans.com/dash/files/b/b3/b3f8148c1d86c9968955529640ded241/0hi4n8khhtf3pgw1wsddp.mpd
2024-09-01 17:09:34.402 +10:00 [DBG] policy: eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjMub25seWZhbnMuY29tXC9kYXNoXC9maWxlc1wvYlwvYjNcL2IzZjgxNDhjMWQ4NmM5OTY4OTU1NTI5NjQwZGVkMjQxXC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI1MjYwNTY0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6Ijg2LjQ4LjguMjQ5XC8zMiJ9fX1dfQ__
2024-09-01 17:09:34.402 +10:00 [DBG] signature: c6yaZnehmwZuZ-iJFdRkNBaZQm0S0Dg8uZo7DiejhAKN-6q5ONToBrIl~GpNf5LgwQFVYS-8DuAjULRFPb~1V4sFpzx6EMUHq5cAIeYnpEK2tpbYWSuhMmf6BmNoMf6t9uCKVgeeCzdZJaAWhmOG1Kins3oTk7lT9fF9THwkX70EzgbXEwtt6DKmFvr~FfHnBisrkdqxYqc~iIH82bo8DvDF85fHsdT9Z9dztr-tiRulweSP8dtxjhbHJdkAFNc7KRwJe1rksGr0SnmElXqrd8~M9NPUxOSuKwaRO~UOCmU4kxuNVHhM-oRzhj7Jljk0n~4-~ihfC69CONVBBO6oGg__
2024-09-01 17:09:34.402 +10:00 [DBG] kvp: K1JM1KV0NHNR73
2024-09-01 17:09:34.471 +10:00 [DBG] Last modified: 22/09/2023 1:57:13 AM
2024-09-01 17:09:34.471 +10:00 [DBG] Calling GetDynamicHeaders
2024-09-01 17:09:34.471 +10:00 [DBG] Path: /api2/v2/users/media/3023388614/drm/post/741715330
2024-09-01 17:09:34.471 +10:00 [DBG] Query Params: ?type=widevine
2024-09-01 17:09:34.471 +10:00 [DBG] Calling GetDecryptionKeyNew
2024-09-01 17:09:35.523 +10:00 [ERR] ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[https @ 0000025c55982ac0] No trailing CRLF found in HTTP header. Adding it.
[tls @ 0000025c559829c0] Error in the push function.
[tls @ 0000025c559829c0] IO error: Error number -10054 occurred
[in#0 @ 0000025c55981380] Error opening input: Error number -10054 occurred
Error opening input file https://cdn3.onlyfans.com/dash/files/b/b3/b3f8148c1d86c9968955529640ded241/0hi4n8khhtf3pgw1wsddp.mpd.
Error opening input files: Error number -10054 occurred

Hopefully that could be of some assistance as the DRM problem is still active.

**Comment by melithine** [comment]
Thanks, folks. We're still not sure exactly what's causing this, but we're going to refactor this section of code to address the problems that are going on and add better logging around it as well. Further logs are not needed at this time, so I'm going to lock the thread but leave it open until we have the refactor completed.

**Comment by melithine** [comment]
Unlocking this. Version 1.7.75 has been released with refactors how ffmpeg is handled, so people who have been affected by this issue should update and test it out. Hopefully this helps you all! And as a side note, it will also tell you at startup if there is a newer version available, so you don't have to keep as close an eye on the Discord server or release notifications through GitHub.

**Comment by DonaldTPP** [comment]
Still having the same problems with DRM enabled users.

**Comment by sim0n00ps** [comment]
If you could please try the latest release, hopefully this has been addressed.
