### ISSUE TITLE
error 403 with DRM files v1.7.74

### ISSUE THREAD

**Issue by Statick** [sim0n00ps/OF-DL#543]
I'm using a VPN and have tried 12 different servers now and the same issue every time
I've updated the auth.json file 
this problem only started since updating to 1.7.74 after the recent site changes

Exception caught: Response status code does not indicate success: 403 (Forbidden).
StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)

**Comment by melithine** [comment]
Are you using your own Widevine keys or CDRM Project?

**Comment by Statick** [comment]
cdrm

**Comment by melithine** [comment]
I suspect that's the issue. If you hit me up on Discord (I'm in the ofdl server as Melithine), I can give you a set of keys.

**Comment by Statick** [comment]
thanks, it's accepted the keys "device_client_id_blob located successfully! device_private_key located successfully!" but I still get the same errors 

Exception caught: Response status code does not indicate success: 403 (Forbidden).
StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)

**Comment by Statick** [comment]
debug log attached

[OFDL20240827.txt](https://github.com/user-attachments/files/16754720/OFDL20240827.txt)

**Comment by aussielimes** [comment]
idk if this is useful information but in 1.7.75 i am still getting this error with most _but not all_ DRM videos

**Comment by Leryn** [comment]
> idk if this is useful information but in 1.7.75 i am still getting this error with most _but not all_ DRM videos

yeah same, i use CDRM Project because honestly i have no idea what Widevine key is.. but never had this issue before

**Comment by aussielimes** [comment]
it's not a CDRM Project issue. I got a set of keys from the discord and the same DRM videos get 403'd, which is also what Statick reported:


StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)

**Comment by sim0n00ps** [comment]
I believe the latest release will fix this, if you could try and let us know

**Comment by aussielimes** [comment]
yes! fixed for me. thank you
