### ISSUE TITLE
Missing download of the first chat message with video

### ISSUE THREAD

**Issue by Cypher4O4** [sim0n00ps/OF-DL#548]
I have tried several times to delete and download the same sub, the first messagge with the vidio attached doesn't appear in free videos folder.

+ Error occurred only while downloading this sub:

- prompt error -
Exception caught: Response status code does not indicate success: 403 (Forbidden).

                                                                    ResponseMessage.EnsureSuccessStatusCode()
Downloading 2 Messages ----------------------------------------  50%licy, String signature, String kvp)

- Log file error -
2024-09-03 06:47:49.081 +02:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)
2024-09-03 18:04:00.564 +02:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)

**Comment by melithine** [comment]
Are you using CDRM Project or your own Widevine keys? Also, try 1.7.75, we reworked how ffmpeg is used and a few other things that might possibly help with this.

**Comment by melithine** [comment]
Please try v1.7.76: https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.76

**Comment by Cypher4O4** [comment]
Same error with last release (v1.7.76)
2024-09-09 11:48:38.869 +02:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)

It creates the folder messages > free > videos but it's empty

I use my own key

**Comment by BigGabagool** [comment]
Getting this error too with the latest with 1.7.76
