### ISSUE TITLE
Auth failed,

### ISSUE THREAD

**Issue by GregCloud** [sim0n00ps/OF-DL#550]
Hello
 I have problem with auth before everything worked now  I dont know what is going on 
from what I see I have a problem with the token 
I don't use any Vpn. I only have changed the DNS to public Google. I don't know if it has any effect. It worked before with the same settings.
any tips that will help solve the problem, thanks in advance

`Exception caught: The SSL connection could not be established, see inner exception.

   StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)

Inner Exception:
Exception caught: Received an unexpected EOF or 0 bytes from the transport stream.

   StackTrace:    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)`

**Comment by melithine** [comment]
That looks like some form of networking issue. You can try 1.7.75 as it refactors a few things, but I suspect it wouldn't solve this and it might just be a local issue for you.

**Comment by GregCloud** [comment]
thanks for the quick reply, I checked version 1.75 and I have the same problem.
but you are right, I share the internet from my phone and everything works fine .
I need to find out what's wrong with my internet Thanks a lot and best regards !.
