### ISSUE TITLE
Unable to download video, file move error

### ISSUE THREAD

**Issue by tingxiangfa** [sim0n00ps/OF-DL#574]
StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
2024-09-21 06:43:30.364 +08:00 [ERR] Exception caught: Could not find file 'D:\download\OFDLV1.7.76\__user_data__\sites\OnlyFans\nana_taipei\Posts\Free\Videos\0hqtveuxtl4rk8v9bn71i_source.mp4'.

The downloaded picture can be successfully renamed, but the video cannot be downloaded, prompting a file move error. But I used to successfully download videos.

**Comment by melithine** [comment]
Try upgrading ffmpeg to 7.0.2.

**Comment by tingxiangfa** [comment]
I have downloaded the latest ffmpeg, but the above problem still exists. There should be no problem with my configuration file, because even if I use the default one directly, the download still fails.
![config](https://github.com/user-attachments/assets/2d617dd9-4651-4d8d-a93a-25d8232607d4)


> 尝试将 ffmpeg 升级到 7.0.2。

I have downloaded the latest ffmpeg, but the above problem still exists. There should be no problem with my configuration file, because even if I use the default one directly, the download still fails.
![config](https://github.com/user-attachments/assets/2d617dd9-4651-4d8d-a93a-25d8232607d4)

**Comment by melithine** [comment]
Are you using your own Widevine keys or CDRM Project?

**Comment by tingxiangfa** [comment]
> 您是否使用自己的 Widevine 密钥或 CDRM 项目？

No

**Comment by melithine** [comment]
It's an a or b question, not yes or no. If you don't have your own keys, cdrm-project is the default. If that's the case, I'm on Discord in the ofdl server as Meliithine and can give you keys if you drop me a PM.

**Comment by melithine** [comment]
@tingxiangfa were you able to get past this?

**Comment by tingxiangfa** [comment]
@melithine I've tried different versions of-dl and ffmpeg, but nothing helps. I can only download pictures now, but cannot download videos. The problem I encountered was mentioned in the previous issue, but I couldn't solve the problem using 1.7.76 and ffmpeg7.0.2 as well as the key provided on discord.
