### ISSUE TITLE
Issue with Widevine after 1.7.79

### ISSUE THREAD

**Issue by glitchronin** [sim0n00ps/OF-DL#591]
After updating to 1.7.78, I have issues with DRM downloads. Here is the output from the logs:

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 13:54:56.811 +08:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at WidevineClient.Widevine.CDM.GetLicenseRequest(String sessionId)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 13:55:57.956 +08:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 14:10:15.266 +08:00 [ERR] Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetPaidPosts(String endpoint, String folder, String username, IDownloadConfig config, List`1 paid_post_ids)
2024-10-05 14:11:17.676 +08:00 [ERR] Exception caught: Unable to decrypt session key

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 14:11:18.965 +08:00 [ERR] Exception caught: Unable to decrypt session key

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 14:11:42.312 +08:00 [ERR] Exception caught: Unable to decrypt session key

StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
2024-10-05 14:12:58.871 +08:00 [ERR] Exception caught: Object reference not set to an instance of an object.

**Comment by melithine** [comment]
Are you using your own keys or cdrm-project?
