### ISSUE TITLE
Unraid - Exception caught: Cannot show selection prompt since the current terminal isn't interactive.

### ISSUE THREAD

**Issue by striker833** [sim0n00ps/OF-DL#600]
Hello, Love the app and have it running fine on windows but would like to move it to my unraid home server on docker. 

I am not the most technical so will try and describe as best as I can.

I have added the repo and the directories to and succesfully pulled the image. I have also configured the auth.json and I can see in the logs the app is succesfully logging in. However it is then encountering an exception and crashing as below. 

I am not sure if this is an issue with the software or something I can resolve in settings? Any help help appreciated.

Logs:
`Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at OF_DL.Program.Main(String[] args) in /src/OF DL/Program.cs:line 390
   at OF_DL.Program.<Main>(String[] args)
/app/entrypoint.sh: line 17:     9 Aborted                 /app/OF\ DL
 __        __         _                                       _             
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___    
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \   
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |  
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/   
                                                                            
   ___    _____           ____    _     
  / _ \  |  ___|         |  _ \  | |    
 | | | | | |_     _____  | | | | | |    
 | |_| | |  _|   |_____| | |_| | | |___ 
  \___/  |_|             |____/  |_____|
                                        
config.json located successfully!
You are running OF-DL version 1.7.79
Latest GitHub Release version: 1.7.79
auth.json located successfully!
rules.json located successfully!
FFmpeg located successfully. Path auto-detected: /usr/bin/ffmpeg
device_client_id_blob and/or device_private_key missing, 
https://cdrm-project.com/ will be used instead for DRM protected videos
Logged In successfully as u6986440 u6986440
Exception caught: Cannot show selection prompt since the current terminal isn't interactive.

StackTrace:    at Spectre.Console.ListPrompt`1.Show(ListPromptTree`1 tree, CancellationToken cancellationToken, Int32 requestedPageSize, Boolean wrapAround) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Prompts\List\ListPrompt.cs:line 28
   at Spectre.Console.SelectionPrompt`1.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Prompts\SelectionPrompt.cs:line 87
   at Spectre.Console.SelectionPrompt`1.Show(IAnsiConsole console) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\Prompts\SelectionPrompt.cs:line 79
   at Spectre.Console.AnsiConsole.Prompt[T](IPrompt`1 prompt) in C:\Users\rhysd\Downloads\spectre.console-0.47.0 mod\spectre.console-0.47.0\src\Spectre.Console\AnsiConsole.Prompt.cs:line 21
   at OF_DL.Program.HandleUserSelection(APIHelper apiHelper, Config currentConfig, Dictionary`2 users, Dictionary`2 lists) in /src/OF DL/Program.cs:line 2247
   at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config) in /src/OF DL/Program.cs:line 470
   at OF_DL.Program.Main(String[] args) in /src/OF DL/Program.cs:line 375

Press any key to exit.

** Press ANY KEY to close this window ** `

**Comment by sim0n00ps** [comment]
You'll probably want to use NonInteractiveMode. @melithine has more experience running in docker than me so hopefully he can explain it better

**Comment by striker833** [comment]
> You'll probably want to use NonInteractiveMode. @melithine has more experience running in docker than me so hopefully he can explain it better

thats fixed it! sorry Im sure thats documented somewhere and Ive missed it. Appreciate the help and fast reply :)

**Comment by melithine** [comment]
https://sim0n00ps.github.io/OF-DL/docs/config/configuration goes over all the options, there's a bunch 😊
