### ISSUE TITLE
"unable to parse license" error 

### ISSUE THREAD

**Issue by Statick** [sim0n00ps/OF-DL#601]
I'm getting the following errors (some lines truncated because that's how they appear)
I'm using CDM keys given from the discord

"Exception caught: Unable to parse license"

"Exception caught: Object reference not set to an instance of an object.
StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agenKey, String folder, DateTimee"

"Exception caught: Unable to parse license
StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Exception caught: Object reference not set to an instance of an object.
StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptio
task, String customFileName, S"

**Comment by NotADeveloper323** [comment]
I'm getting this with one of the models too

**Comment by nachoman91** [comment]
Got this error with 8.0 now, any solution?
