### ISSUE TITLE
I updated to 1.7.79 and am getting this error, only when I try to download videos. it can download pics just fine.

### ISSUE THREAD

**Issue by mantis0777** [sim0n00ps/OF-DL#602]
Exception caught: Response status code does not indicate success: 504 (Gateway Time-out).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, Stri                                                              folder, DateTime lastModified, Int64 media_id, String api_
Downloading Post ----------------------------------------   0%e, String path)

It used to say roughly the same thing but with a 500 error

**Comment by melithine** [comment]
Are you using your own Widevine keys or cdrm-project? The latter is the default, but it relies on a third party server that is sometimes flaky. If you post in our Discord we can get you keys.
