### ISSUE TITLE
Auth Failed though file is correct

### ISSUE THREAD

**Issue by jonk999** [sim0n00ps/OF-DL#603]
Was working fine but am now getting an Auth Failed error.
Chrome updated on 16/10, however I've checked the auth details both manually and using the chrome extension so the auth file should be correct. It didn't appear as though anything changed as part of the Chrome update in terms of auth details.

From log:
StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint)
2024-10-18 17:42:27.606 +10:00 [ERR] Inner Exception: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..

StackTrace:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2024-10-18 17:42:27.610 +10:00 [ERR] Auth failed

**Comment by jonk999** [comment]
I have since found, if I rename the folder and then run it again it works fine. But if I rename it back, it fails Auth again. I'm wondering if it's my anti-virus doing something. I've had issues with Google Drive desktop lately as well that stop when I temporarily stop it. When it next happens I'll try disabling it and see if it then works without renaming the folder.
