### ISSUE TITLE
DRM videos not downloaded when running natively on Linux

### ISSUE THREAD

**Issue by modelfe** [sim0n00ps/OF-DL#629]
Running this natively on Linux [as described here](https://sim0n00ps.github.io/OF-DL/docs/installation/linux) isn't downloading any DRM videos. 

Non-DRM content downloads fine. No problem downloading DRM videos on Windows. I haven't tried running it in Docker yet.

Output example:

```
cd "OF-DL/OF DL/bin/Release/net8.0"
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 ./'OF DL'
 __        __         _                                       _             
 \ \      / /   ___  | |   ___    ___    _ __ ___     ___    | |_    ___    
  \ \ /\ / /   / _ \ | |  / __|  / _ \  | '_ ` _ \   / _ \   | __|  / _ \   
   \ V  V /   |  __/ | | | (__  | (_) | | | | | | | |  __/   | |_  | (_) |  
    \_/\_/     \___| |_|  \___|  \___/  |_| |_| |_|  \___|    \__|  \___/   
                                                                            
   ___    _____           ____    _     
  / _ \  |  ___|         |  _ \  | |    
 | | | | | |_     _____  | | | | | |    
 | |_| | |  _|   |_____| | |_| | | |___ 
  \___/  |_|             |____/  |_____|
                                        
config.json located successfully!
You are running OF-DL version 1.7.83
Latest GitHub Release version: 1.7.83
auth.json located successfully!
rules.json located successfully!
FFmpeg located successfully. Path auto-detected: /usr/bin/ffmpeg
device_client_id_blob and/or device_private_key missing, 
https://cdrm-project.com/ will be used instead for DRM protected videos
Logged In successfully as xxx
Downloading from List(s): xxx
Scraping Data for xxx
Folder for xxx already created
Getting Messages
Found 5 Media from xxx Messages
                                                                    
Downloading 5 Messages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%
                                                                    Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.DownloadHelper.OnError(Object sender, ConversionErrorEventArgs e) in /home/xxx/OF-DL/OF DL/Helpers/DownloadHelper.cs:line 942
   at FFmpeg.NET.Engine.OnError(ConversionErrorEventArgs e)
   at FFmpeg.NET.FFmpegProcess.OnConversionError(ConversionErrorEventArgs eventArgs)
   at FFmpeg.NET.FFmpegProcess.OnException(List`1 messages, FFmpegParameters parameters, Int32 exitCode, Exception caughtException)
   at FFmpeg.NET.FFmpegProcess.ExecuteAsync(ProcessStartInfo startInfo, FFmpegParameters parameters, CancellationToken cancellationToken)
   at FFmpeg.NET.FFmpegProcess.ExecuteAsync(CancellationToken cancellationToken)
   at FFmpeg.NET.Engine.ExecuteAsync(FFmpegParameters parameters, CancellationToken cancellationToken)
   at FFmpeg.NET.Engine.ExecuteAsync(String arguments, CancellationToken cancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, Progre                                                                     

```

**Comment by melithine** [comment]
What version of ffmpeg?

**Comment by modelfe** [comment]
> What version of ffmpeg?

ffmpeg version 4.4.2-0ubuntu0.22.04.1

**Comment by melithine** [comment]
You really want 7.0.2 or newer. Some older 6.x releases are fine, too, but I'm not sure which, and people have had the most luck with 7.0.2+.

**Comment by cactus1902** [comment]
On Linux I can confirm that on the latest snapshot of ffmpeg (https://ffmpeg.org/releases, scroll down to "ffmpeg-snapshot.tar.bz2", version is 2024-11-20 19:26 at the time of writing this), DRM videos do not work; regular videos do. DRM videos also download fine on Windows as OP said.

All other versions of ffmpeg that I have (version 6, 7.02, 20240504, and 20240629) have the same issue with DRM content.

**Comment by braedanman** [comment]
Hello, I am also having the same issue. I am running Docker on Mac and can confirm I have the latest release of ffmpeg but I still get the same error message as the original poster. It will not download DRM videos.

**Comment by melithine** [comment]
> Hello, I am also having the same issue. I am running Docker on Mac and can confirm I have the latest release of ffmpeg but I still get the same error message as the original poster. It will not download DRM videos.

Docker doesn't use the version of ffmpeg on your computer, it uses one inside the container which should be fine. (I use the Docker image pretty much exclusively unless I'm specifically testing something in Windows.) Are you using your own CDM keys or cdrm-project?

**Comment by braedanman** [comment]
cdrm-project, is that what is causing issues?

**Comment by melithine** [comment]
Potentially. Check in the Discord server, I or one of the other folks can give you keys.
