### ISSUE TITLE
error when downloading, FFmpeg error? 

### ISSUE THREAD

**Issue by charlieorwell** [sim0n00ps/OF-DL#631]
Have this error pop up when I'm trying to download, not sure if it's a bug or not. 
pixelated stuff is just file paths for something it's trying to download but it says it's missing? Basically where the first part of the error says ''FFmpeg failed to download..." 

anyone know if there's a fix for this or just ignore it? 

![screenshot 240](https://github.com/user-attachments/assets/3ca808be-05a1-493c-a03a-d2a6b0dfe2b9)

**Comment by melithine** [comment]
What version are you on?

**Comment by charlieorwell** [comment]
> What version are you on?

1.7.74 

would updating fix this?

**Comment by Nemes94** [comment]
![image](https://github.com/user-attachments/assets/9df383bd-3aa5-4aea-932c-555bbc1ac1c1)
StackTrace:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at OF_DL.Helpers.APIHelper.GetDynamicRules()

Inner Exception:
Exception caught: The connection attempt failed because the connected partner did not respond within the specified time or there was an error in the established connection because the connected partner was unable to respond.

StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

**Comment by melithine** [comment]
> > What version are you on?
> 
> 1.7.74
> 
> would updating fix this?

We are almost ten versions more recent than that. Definitely upgrade and open a new issue if the problem persists.
