### ISSUE TITLE
[ERR] Exception caught: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by naiai49** [sim0n00ps/OF-DL#635]
When I made the mistake of downloading

StackTrace:    at OF_DL.Helpers.DownloadHelper.OnError(Object sender, ConversionErrorEventArgs e)
   at FFmpeg.NET.Engine.OnError(ConversionErrorEventArgs e)
   at FFmpeg.NET.FFmpegProcess.OnConversionError(ConversionErrorEventArgs eventArgs)
   at FFmpeg.NET.FFmpegProcess.OnException(List`1 messages, FFmpegParameters parameters, Int32 exitCode, Exception caughtException)
   at FFmpeg.NET.FFmpegProcess.ExecuteAsync(ProcessStartInfo startInfo, FFmpegParameters parameters, CancellationToken cancellationToken)
   at FFmpeg.NET.FFmpegProcess.ExecuteAsync(CancellationToken cancellationToken)
   at FFmpeg.NET.Engine.ExecuteAsync(FFmpegParameters parameters, CancellationToken cancellationToken)
   at FFmpeg.NET.Engine.ExecuteAsync(String arguments, CancellationToken cancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)

**Comment by naiai49** [comment]
[OFDL20241112.txt](https://github.com/user-attachments/files/17705403/OFDL20241112.txt)

**Comment by codedragonnnnn** [comment]
Have you solved this problem yet? I have encountered the same problem

**Comment by deadbeatdandylyon** [comment]
Just a user attempting to help

What version of FFmpeg are you using? 
Do you have the path name correctly entered into the `config.json` file?
Also confirm that the \ are switched to / in the ffmpeg path name

**Comment by codedragonnnnn** [comment]
> Just a user attempting to help
> 
> What version of FFmpeg are you using? Do you have the path name correctly entered into the file? Also confirm that the \ are switched to / in the ffmpeg path name`config.json`

The FFmpeg version I am using is 7.1. I downloaded and extracted it to D drive, and then set the path to "D:/ffmpeg-7.1-essentials_build/bin/ffmpeg.exe" directly in the config.json.

**Comment by deadbeatdandylyon** [comment]
Is there any way you can share the whole line it's self for the `ffmpegpath`
Example:  `"FFmpegPath": "C:/Users/<user>/Downloads/OFDLV1.7.83/Scraper Programs/ffmpeg-7.1-essentials_build/bin/ffmpeg.exe",`

Just to make sure even the beginning part of the ffmpeg path is correct, also to confirm you do have the latest version of OFDL installed 1.7.83

**Comment by codedragonnnnn** [comment]
> Is there any way you can share the whole line it's self for the `ffmpegpath` Example: `"FFmpegPath": "C:/Users/<user>/Downloads/OFDLV1.7.83/Scraper Programs/ffmpeg-7.1-essentials_build/bin/ffmpeg.exe",`
> 
> Just to make sure even the beginning part of the ffmpeg path is correct, also to confirm you do have the latest version of OFDL installed 1.7.83

Yes. The settings in my current config. json are: "FFmpegPath": "D:/OFDLV1.7.83/ffmpeg-7.1-essentials_build/bin/ffmpeg. exe". I am certain that I have downloaded the latest version

**Comment by deadbeatdandylyon** [comment]
Just curious in your `config.json` file, where the ffmpeg path is. if you have a period at the end after the quotation marks, try changing that to a comma, that's the only thing I can see different between my path and yours

**Comment by codedragonnnnn** [comment]
> Just curious in your `config.json` file, where the ffmpeg path is. if you have a period at the end after the quotation marks, try changing that to a comma, that's the only thing I can see different between my path and yours

That's just the end of my sentence. It is correct in the config. json.

**Comment by deadbeatdandylyon** [comment]
Can you try to move your `FFmpeg.exe` file into the same directory folder as your `OFDLV1.7.83` and see if that makes any difference? and update your ffmpeg path in the config file to the new path. 

If that still doesn't work then I would try to redownload the ffmpeg by going to the following site https://www.gyan.dev/ffmpeg/builds/ and downloading the zip again [ffmpeg-release-essentials.zip] for the 7.1, you can also try the version of 7.0.2 if 7.1 continues to provide issues. 

IF you have tried both then I would wait to someone more knowledge can help or reach them through the discord for further assistance.

**Comment by codedragonnnnn** [comment]
> Can you try to move your `FFmpeg.exe` file into the same directory folder as your `OFDLV1.7.83` and see if that makes any difference? and update your ffmpeg path in the config file to the new path.
> 
> If that still doesn't work then I would try to redownload the ffmpeg by going to the following site https://www.gyan.dev/ffmpeg/builds/ and downloading the zip again [ffmpeg-release-essentials.zip] for the 7.1, you can also try the version of 7.0.2 if 7.1 continues to provide issues.
> 
> IF you have tried both then I would wait to someone more knowledge can help or reach them through the discord for further assistance.

I have tried all the methods you mentioned, but the result is still the same. Anyway, thank you for your help~

**Comment by deadbeatdandylyon** [comment]
Can I confirm with you if this is when you scrape a profile? and is it the same persons page, or have you tried other creators?

**Comment by melithine** [comment]
Are you using a VPN? If so, can you try without it?

**Comment by codedragonnnnn** [comment]
> Are you using a VPN? If so, can you try without it?

Yes. I won't be able to log in to Onlyfans without using VPN.

**Comment by melithine** [comment]
Try a different VPN endpoint location or provider, then.

**Comment by codedragonnnnn** [comment]
> Try a different VPN endpoint location or provider, then.

I downloaded content from two creators using the same endpoint, and I found that one failed and the other succeeded. I guess this issue is related to DRM protection.

**Comment by deadbeatdandylyon** [comment]
I don't use a VPN and I've been scraping perfectly fine DRM and non DRM, you can try to delete the metadata folder in the creators folder and then try again, but I don't believe that it is DRM related

**Comment by codedragonnnnn** [comment]
> I don't use a VPN and I've been scraping perfectly fine DRM and non DRM, you can try to delete the metadata folder in the creators folder and then try again, but I don't believe that it is DRM related

Okay, I will do more testing~ By the way, how can I distinguish whether a content is DRM or non DRM？

**Comment by deadbeatdandylyon** [comment]
There are two ways that I personally know of 1) usually if you go to play the video the quality would be set to auto and you would have to manually switch to original, 2) the easiest way for you to know is if you download the extension "downloader for onlyfans" even though it doesn't work, if it doesn't show an option to download anything usually the videos are set to DRM if does show the work original or video to download then it doesn't have DRM

these are the only known ways i personally have figured out to tell the difference

**Comment by codedragonnnnn** [comment]
> Try a different VPN endpoint location or provider, then.

I think switching VPN endpoints is useless.

**Comment by codedragonnnnn** [comment]
> There are two ways that I personally know of 1) usually if you go to play the video the quality would be set to auto and you would have to manually switch to original, 2) the easiest way for you to know is if you download the extension "downloader for onlyfans" even though it doesn't work, if it doesn't show an option to download anything usually the videos are set to DRM if does show the work original or video to download then it doesn't have DRM
> 
> these are the only known ways i personally have figured out to tell the difference

I have enabled the extension “downloader for onlyfans” and found that the content of the creator I just downloaded successfully is non DRM, so I believe this issue is related to DRM.

**Comment by codedragonnnnn** [comment]
> There are two ways that I personally know of 1) usually if you go to play the video the quality would be set to auto and you would have to manually switch to original, 2) the easiest way for you to know is if you download the extension "downloader for onlyfans" even though it doesn't work, if it doesn't show an option to download anything usually the videos are set to DRM if does show the work original or video to download then it doesn't have DRM
> 
> these are the only known ways i personally have figured out to tell the difference

I just found a creator whose content is mixed with DRM and non DRM, so my download is mixed with success and failure, which confirms my hypothesis.

**Comment by deadbeatdandylyon** [comment]
At this point not sure, If I was able to test it for you I would 

but aside from that, the only way to know i think at this point, you can try to get authentication information using another browser as opposed to the one that you're using. As mentioned, I've been able to scrape DRM profile without issue. 

you can try to see also as an alternative to bring your computer up in safe mode with networking and see if maybe something installed in your system could be causing a problem.

**Comment by deadbeatdandylyon** [comment]
I'm on the OF discord if you want to reach out

**Comment by codedragonnnnn** [comment]
> At this point not sure, If I was able to test it for you I would
> 
> but aside from that, the only way to know i think at this point, you can try to get authentication information using another browser as opposed to the one that you're using. As mentioned, I've been able to scrape DRM profile without issue.
> 
> you can try to see also as an alternative to bring your computer up in safe mode with networking and see if maybe something installed in your system could be causing a problem.



> I'm on the OF discord if you want to reach out

Sorry, I am a non-native English speaker and I cannot understand this sentence.May I ask if you could rephrase it？ I will test it on other browsers later.

**Comment by deadbeatdandylyon** [comment]
You can join the OF DL discord [here](https://discord.com/invite/6bUW8EJ53j) for further assistance

Safe mode with networking you can google it

**Comment by melithine** [comment]
> I have enabled the extension “downloader for onlyfans” and found that the content of the creator I just downloaded successfully is non DRM, so I believe this issue is related to DRM.

Are you using your own CDM keys or cdrm-project? (You will see a yellow warning message at startup if you do not have your own keys). The reason I ask is two-fold; OnlyFans tends to rate limit connections, which affects both regular VPN usage (thus the suggestion about endpoints/providers) and cdrm-project itself (which can be avoided by using keys, which you can get on Discord if you don't want the hassle of generating them yourself, as it is a rather technical process to do). If you're using cdrm-project and a VPN, then yes, switching endpoints/providers likely won't help, but it is something many VPN users who do have keys have found helps. OnlyFans does not like VPNs, but they obviously can't know all IP addresses for all locations and providers, so that's why switching helps, but again, that won't help much if cdrm-project is the limiting factor.

Since non-DRM videos work fine for you, I suspect that you are hitting the cdrm-project rate limiting, as that's not used if the video to download doesn't have DRM.

**Comment by codedragonnnnn** [comment]
Are you referring to this warning?"device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM protected videos"        How do I get the key on Discord? How can I find you?I have accepted the invitation and my ID is coded.

**Comment by melithine** [comment]
Yes, that's the one. DM'd you keys on Discord.

**Comment by codedragonnnnn** [comment]
> You can join the OF DL discord [here](https://discord.com/invite/6bUW8EJ53j) for further assistance
> 
> Safe mode with networking you can google it

I have used these two files but still face the same problem."device_client_id_blob" ,"device_private_key missing"

**Comment by codedragonnnnn** [comment]
> You have to make sure that the CDM keys that were provided are put into the CDM folder within the OFDL directory, It seems like you were provided the keys through Discord,

I am quite certain that my file structure is correct. The original empty CDM folder has been replaced. There is no longer a yellow warning when starting up.You can send a private message to my discord, my ID is coded, and I will provide a screenshot.

**Comment by deadbeatdandylyon** [comment]
@sim0n00ps and @melithine 

Just wanted to provide some information into this thread to see if maybe someone else is having the same problem or one of you two can test further information. 

I can't speak on behalf of the original poster that made this thread, but the second person @codedragonnnnn and now another user that posted in the discord goes by Nik seem to both be in the location of China, I worked with @codedragonnnnn and was able to confirm had the correct python versions, had the correct FFmpeg versions, the path name for ffmpeg was correct within the config.json path, 

Aside from them both being in the China area and both being on a VPN I don't believe they share any other similarities other then when it comes to DRM content they run into this problem

The way that I tested was I was able to scrape the account that @codedragonnnnn was trying to but i'm located in the US and I don't have a VPN or any antivirus software and was able to complete the scrape without any complications. 

Is there something you guys can look into this further? 

this is also the image that the person Nik shared similar error message

![image](https://github.com/user-attachments/assets/6996aee9-d4cb-454c-a660-cf8fe54151a3)
