### ISSUE TITLE
Unable to parse license

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#652]
Mostly I have no such errors but sometimes I got a lot of them

 Exception caught: Unable to parse license

                                                                                                             StackTrace:    at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license)
   at WidevineClient.Widevine.CDMApi.ProvideLicense(String licenseB64)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptio                                                                    pi_type, ProgressTask task, String customFileName, S
D

**Comment by bezaaas** [comment]
Any solutions?

**Comment by atriswindu** [comment]
I also started getting these messages recently. It happened after I updated from 1.7.83 to 1.8.0 and switched from using the web to local CDM. I'm not sure which caused it.
