### ISSUE TITLE
could not download drm video

### ISSUE THREAD

**Issue by hebeebee** [sim0n00ps/OF-DL#68]
After the following error message appears, it can be downloaded normally, but the downloaded DRM video cannot be synthesized for viewing

 Exception caught: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (cdrm-project.com:443)

                                                                                 StackTrace:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DRM_Video_Downloader.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

                                                                                        StackTrace:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
                                                                                          tableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

**Comment by Puk0** [comment]
Es porque no conecta con "(cdrm-project.com:443)", se queda esperando la key drm y asi se quedan los archivos encriptados o en archivo .part

**Comment by sim0n00ps** [comment]
As I have stated in other issues raised by people it's because cdrm-project is down, nothing I can do about it right now
