### ISSUE TITLE
Item with the same key

### ISSUE THREAD

**Issue by miglety** [sim0n00ps/OF-DL#90]
Running the latest, just got this:

```
Exception caught: An item with the same key has already been added. Key: modelsnameremoved

                                                                                      StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at OF_DL.Helpers.APIHelper.GetSubscriptions(String endpoint, Boolean includeExpiredSubscriptions, Auth auth)
```

Then if i press anything it just closes the app

**Comment by sim0n00ps** [comment]
Yeah this is an easy fix I'll create a new release with the fix

**Comment by sim0n00ps** [comment]
Try latest release
