### ISSUE TITLE
Help needed with dumper

### ISSUE THREAD

**Issue by CaptainKoons** [sim0n00ps/OF-DL#93]
Hi!

Sorry for asking here, but at the dumper domain nobody is responding.
And also sorry for possibly asking stupid questions – I have little to no experience in programming… :-)

I created a virtual android device.
Installed Frida & and put it on the phone.
I ran these commands:

> adb.exe shell
> su
> mv /sdcard/frida-server-16.1.1-android-x86 /data/local/tmp
> chmod +x /data/local/tmp/frida-server-16.1.1-android-x86
> /data/local/tmp/frida-server-16.1.1-android-x86

I downloaded dumper and installed the requirements
Then I tried to run dump_keys.py, but got the following errors:

> C:\Users\TR\Downloads\dumper-main
> λ Python dump_keys.py
> Traceback (most recent call last):
> File "C:\Users\TR\Downloads\dumper-main\dump_keys.py", line 6, in 
> from Helpers.Scanner import Scan
> File "C:\Users\TR\Downloads\dumper-main\Helpers\Scanner.py", line 7, in 
> from Helpers.wv_proto2_pb2 import SignedLicenseRequest
> File "C:\Users\TR\Downloads\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in 
> _descriptor.EnumValueDescriptor(
> File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\descriptor.py", line 796, in new
> _message.Message._CheckCalledFromGeneratedFile()
> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
> 1.	Downgrade the protobuf package to 3.20.x or lower.
> 2.	Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
> 

Any ideas what I’m doing wrong?
Many thanks in advance!
CK

**Comment by sim0n00ps** [comment]
Run this:
pip install protobuf==3.20.3

**Comment by mediaburnwayne** [comment]
I had same issue and that protobuf version was the issue

**Comment by CaptainKoons** [comment]
> Run this: pip install protobuf==3.20.3

Big thanks for your quick and helpful feedback!
Dumper worked fine now. 
And above all, your magnificent OF-DL-tool works finally great again.  :-)
