### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by edge-evolution** [sim0n00ps/OF-DL#95]
Been having some issues, updated to the newest version from a couple of days ago. I get this now.  

See below:

Exception caught: SQLite Error 14: 'unable to open database file'.

                                 StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at OF_DL.Helpers.DBHelper.UpdateMedia(String folder, Int64 media_id, String directory, String filename, Int64 size, Boolean downloaded, DateTime created_at)
   at OF_DL.Helpers.DownloadHelper.DownloadPostMedia(String url, String folder, Int64 media_id, ProgressTask task)
Exception caught: SQLite Error 14: 'unable to open database file'.

                                                                  StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)

**Comment by edge-evolution** [comment]
Only the files from the package. They are all in the same folder. I restarted a few times, but now I'm getting a different error. It opens up, and then I select the profile I want to download from. I get an error about not being able to obtain file size.

**Comment by sim0n00ps** [comment]
Do you have a .DLL file within the folder?

**Comment by edge-evolution** [comment]
Yes I do. The e_sqlite3.dll file.
